<!-- Récupération des variables -->
<?php

$translate = $this->getParam('translate');

// var_dump($translate);

?>



<!-- Formulaire de connexion basique -->
<div class="mdl-cell mdl-cell--4-col"></div>
<form action="/auth/login/" method="POST" class="mdl-cell mdl-cell--4-col">
  <div class="mdl-card mdl-shadow--8dp">
    <div class="mdl-card__title goodyear-color--light">
      <h2 class="mdl-card__title-text mdl-color-text--white titreConnexion"><?= $this->getVerifyTranslate($translate, 'connectTitle') ?></h2>
    </div>
    <div class="mdl-card__supporting-text">
      <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-cell mdl-cell--10-col login" autocomplete="off">
        <input class="mdl-textfield__input" type="text" name="login" id="login" autocomplete="off" maxlength="15">
        <label class="mdl-textfield__label" for="login"><?= $this->getVerifyTranslate($translate, 'loginTitle') ?></label>
      </div>
      <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-cell mdl-cell--10-col login" autocomplete="off">
        <input class="mdl-textfield__input" type="password" name="pwd" autocomplete="off" id="pwd">
        <label class="mdl-textfield__label" for="pwd"><?= $this->getVerifyTranslate($translate, 'passwordTitle') ?></label>
      </div>
    </div>
    <div class="mdl-card__actions mdl-card--border">
      <input type="submit" class="mdl-button mdl-js-button mdl-button--raised goodyear-color--light mdl-color-text--white valider" />
    </div>
  </div>
</form>
<div class="mdl-cell mdl-cell--4-col"></div>
