<!-- Récupération des données en PHP -->
<?php

$dataID = $this->getParam('dataID');

$mold = $this->getParam('mold');

$patternSizeList = $this->getParam('patternSizeList');

$refSpecs = $this->getParam('refSpecs');

$statusList = $this->getParam('statusList');
$translateStatusList = $this->getParam('translateStatusList');

$locationTypeList = $this->getParam('locationTypeList');
$translateLocationTypeList = $this->getParam('translateLocationTypeList');

$dataList = $this->getParam('dataList');
$translateData = $this->getParam('translateData');

$dataCategoryList = $this->getParam('dataCategoryList');
$translateDataCategory = $this->getParam('translateDataCategory');

$dataRule = $this->getParam('dataRule');

$translate = $this->getParam('translate');


// var_dump($dataID);

// var_dump($mold);

// var_dump($patternSizeList);

//  var_dump($refSpecs);

// var_dump($statusList);
// var_dump($translateStatusList);

// var_dump($locationTypeList);
// var_dump($translateLocationTypeList);

// var_dump($dataList);
// var_dump($translateData);

// var_dump($dataCategoryList);
// var_dump($translateDataCategory);

// var_dump($dataRule);

// var_dump($translate);


// Outils pour les fonctions nécessaire
$toolsController = new toolsController();

?>



<!-- Feuille de style CSS de la page -->
<style type="text/css">
  .middle {
    text-align: center !important;
  }

  .title {
    font-weight: bold;
  }
</style>



<!-- Formulaire d'ajout d'un moule -->
<div class="mdl-cell mdl-cell--12-col mdl-card">
  <!-- Titre du formulaire -->
  <div class="mdl-card__title goodyear-color--light goodyear-color-text">
    <h6 class="mdl-card__title-text title"><?= $this->getVerifyTranslate($translate, 'editFormTitle') . ' ' . $dataID ?></h6>
  </div>

  <!-- Contenu du formulaire -->
  <form id="edit_form" method="post" action="/mold/edit" class="mdl-card__supporting-text mdl-grid">
    <!-- Ajout de l'identifiant unique du moule -->
    <input class="hidden" type="text" value="<?= $mold['REF_MOULE'] ?>" name="REF_MOULE">
    <!-- Affichage des catégorie -->
    <?php foreach ($dataCategoryList as $categoryBaseName => $color) : ?>
      <div class="mdl-cell mdl-cell--6-col">
        <div class="mdl-card mdl-shadow--8dp">
          <!-- Titre de la catégorie -->
          <div class="mdl-card__title" style="background-color: #<?= $color ?>; color: <?= $toolsController->autoTextColor('#' . $color) ?>">
            <h6 class="mdl-card__title-text title"><?= $this->getVerifyTranslate($translateDataCategory, $categoryBaseName) ?></h6>
          </div>

          <!-- Contenu de la catégorie -->
          <div class="mdl-card__supporting-text mdl-grid">
            <?php foreach ($dataList as $dataBaseName => $data) : ?>
              <?php if ($data['category']['name'] == $categoryBaseName and isset($dataRule[$dataBaseName]['edit'])) : ?>
                <!-- Définition des saisi pour les champs spéciaux -->
                <?php switch ($dataBaseName):
                        default: ?>
                    <!-- Zone de texte par défaut -->
                    <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-cell mdl-cell--3-col">
                      <input id="<?= $dataBaseName ?>" class="mdl-textfield__input" type="text" name="<?= $dataBaseName ?>" value="<?= $mold[$dataBaseName] ?>">
                      <label class="mdl-textfield__label"><?= $this->getVerifyTranslate($translateData, $data['name']) ?></label>
                    </div>
                    <?php break; ?>

                  <?php
                        case 'PATTERNSIZE': ?>
                    <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-cell mdl-cell--6-col">
                      <input id="<?= $dataBaseName ?>" list="<?= $dataBaseName ?>_items" class="mdl-textfield__input" type="text" name="<?= $dataBaseName ?>" value="<?= $mold[$dataBaseName] ?>">
                      <datalist id="<?= $dataBaseName ?>_items">
                        <?php foreach ($patternSizeList as $key => $patternSize) : ?>
                          <option><?= $patternSize['PATTERNSIZE'] ?></option>
                        <?php endforeach; ?>
                      </datalist>
                      <label class="mdl-textfield__label"><?= $this->getVerifyTranslate($translateData, $data['name']) ?></label>
                    </div>
                    <?php break; ?>

                  <?php
                        case 'GRADES': ?>
                    <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-cell mdl-cell--6-col">
                      <input id="<?= $dataBaseName ?>" class="mdl-textfield__input" type="text" name="<?= $dataBaseName ?>" value="<?= $mold[$dataBaseName] ?>">
                      <label class="mdl-textfield__label"><?= $this->getVerifyTranslate($translateData, $data['name']) ?></label>
                    </div>
                    <?php break; ?>

                  <?php
                        case 'NB_CYCLE_CUISSON_LIFE':
                        case 'NB_CYCLE_CUISSON_NOW': ?>
                    <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-cell mdl-cell--6-col">
                      <input id="<?= $dataBaseName ?>" class="mdl-textfield__input" type="text" pattern="^[-+]?[0-9]*\,?[0-9]+$" name="<?= $dataBaseName ?>" value="<?= $mold[$dataBaseName] ?>">
                      <label class="mdl-textfield__label"><?= $this->getVerifyTranslate($translateData, $data['name']) ?></label>
                      <span class="mdl-textfield__error"><?= $this->getVerifyTranslate($translate, 'errorNumberInput') ?></span>
                    </div>
                    <?php break; ?>

                  <?php
                        case 'S_DIAMETRE':
                        case 'L_DIAMETRE':
                        case 'JEUX_TOTAL_SECTEUR': ?>
                    <input id="<?= $dataBaseName ?>" name="<?= $dataBaseName ?>" value="<?= $mold[$dataBaseName] ?>" hidden>
                    <?php break; ?>

                  <?php
                        case 'LOCATION': ?>
                    <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-cell mdl-cell--3-col">
                      <input id="<?= $dataBaseName ?>" class="mdl-textfield__input" type="text" name="<?= $dataBaseName ?>" value="<?= $mold['LOCATION_CHOICE'] ?>">
                      <label class="mdl-textfield__label"><?= $this->getVerifyTranslate($translateData, $data['name']) ?></label>
                    </div>
                    <?php break; ?>

                  <?php
                        case 'STATUT':
                        case 'LOCATION_TYPE': ?>
                    <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-cell mdl-cell--6-col">
                      <select id="<?= $dataBaseName ?>" class="mdl-textfield__input" type="text" name="<?= $dataBaseName ?>">
                        <?php switch ($dataBaseName):
                                  case 'STATUT': ?>
                            <?php foreach ($statusList as $id => $status) : ?>
                              <option value="<?= $status['STATUS_MOULE'] ?>" <?= $mold[$dataBaseName] == $status['STATUS_MOULE'] ? 'selected' : '' ?>><?= $this->getVerifyTranslate($translateStatusList, $status['STATUS_MOULE']) ?></option>
                            <?php endforeach; ?>
                            <?php break; ?>

                          <?php
                                  case 'LOCATION_TYPE': ?>
                            <?php foreach ($locationTypeList as $id => $location) : ?>
                              <option value="<?= $location['LOCATION_TYPE'] ?>" <?= $mold[$dataBaseName] == $location['LOCATION_TYPE'] ? 'selected' : '' ?>><?= $this->getVerifyTranslate($translateLocationTypeList, $location['LOCATION_TYPE']) ?></option>
                            <?php endforeach; ?>
                            <?php break; ?>
                          <?php endswitch; ?>
                      </select>
                      <label class="mdl-textfield__label" style="top: 1px;"><?= $this->getVerifyTranslate($translateData, $data['name']) ?></label>
                    </div>
                    <?php break; ?>

                  <?php
                        case 'POSITION_ACTUEL_DATE': ?>
                    <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-cell mdl-cell--12-col">
                      <input id="<?= $dataBaseName ?>" class="mdl-textfield__input" type="datetime-local" name="<?= $dataBaseName ?>" value="<?= $mold[$dataBaseName] ? date_create_from_format('d-m-Y H:i:s', $mold[$dataBaseName])->format('Y-m-d\TH:i:s') : '' ?>" />
                      <label class="mdl-textfield__label" style="top: 7px;"><?= $this->getVerifyTranslate($translateData, $data['name']) ?></label>
                    </div>
                    <?php break; ?>

                  <?php
                        case 'START_DATE':
                        case 'END_DATE':
                        case 'LAST_CHECK_DATE':
                        case 'DATE_LAST_ENVELOPPE':
                        case 'DATE_GET_MOLD': ?>
                    <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-cell mdl-cell--6-col">
                      <input id="<?= $dataBaseName ?>" class="mdl-textfield__input" type="datetime-local" name="<?= $dataBaseName ?>" style="margin-top: -6px;" value="<?= $mold[$dataBaseName] ? date_create_from_format('d-m-Y H:i:s', $mold[$dataBaseName])->format('Y-m-d\TH:i:s') : '' ?>" />
                      <label class="mdl-textfield__label" style="top: 1px;"><?= $this->getVerifyTranslate($translateData, $data['name']) ?></label>
                    </div>
                    <?php break; ?>

                  <?php
                        case 'LAST_RESULT': ?>
                    <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-cell mdl-cell--6-col">
                      <select id="<?= $dataBaseName ?>" class="mdl-textfield__input full" type="text" name="<?= $dataBaseName ?>">
                        <option value="okMetro" <?= $mold[$dataBaseName] == 'okMetro' ? 'selected' : '' ?>><?= $this->getVerifyTranslate($translate, 'okMetro') ?></option>
                        <option value="notOkMetro" <?= $mold[$dataBaseName] == 'notOkMetro' ? 'selected' : '' ?>><?= $this->getVerifyTranslate($translate, 'notOkMetro') ?></option>
                        <option value="maybeMetro" <?= $mold[$dataBaseName] == 'maybeMetro' ? 'selected' : '' ?>><?= $this->getVerifyTranslate($translate, 'maybeMetro') ?></option>
                      </select>
                      <label class="mdl-textfield__label" style="top: 1px;"><?= $translateData[$data['name']] ?></label>
                    </div>
                    <?php break; ?>

                  <?php
                        case 'CLOGGED_HOLES': ?>
                    <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-cell mdl-cell--3-col">
                      <select id="<?= $dataBaseName ?>" class="mdl-textfield__input full" type="text" name="<?= $dataBaseName ?>">
                        <option value="Y" <?= $mold[$dataBaseName] == null ? 'selected' : '' ?>><?= $this->getVerifyTranslate($translate, 'cloggedHolesOK') ?></option>
                        <option value="" <?= $mold[$dataBaseName] == null ? 'selected' : '' ?>><?= $this->getVerifyTranslate($translate, 'cloggedHolesNO') ?></option>
                      </select>
                      <label class="mdl-textfield__label" style="top: 1px;"><?= $this->getVerifyTranslate($translateData, $data['name']) ?></label>
                    </div>
                    <?php break; ?>

                  <?php
                        case 'COMMENTAIRE':
                        case 'COMMENT_EXCEPT':
                        case 'COMMENT_METRO':
                        case 'CAUSE_GRADE': ?>
                    <div id="<?= $dataBaseName ?>" class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-cell mdl-cell--12-col">
                      <textarea class="mdl-textfield__input" type="text" rows="3" name="<?= $dataBaseName ?>"><?= $mold[$dataBaseName] ?></textarea>
                      <label class="mdl-textfield__label"><?= $this->getVerifyTranslate($translateData, $data['name']) ?></label>
                    </div>
                    <?php break; ?>
                  <?php
                        case 'REF_SPECS': ?>
                    <div id="<?= $dataBaseName ?>" class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-cell mdl-cell--6-col">
                      <!-- <textarea class="mdl-textfield__input" type="text" rows="3" name="<?= $dataBaseName ?>"><?= $mold[$dataBaseName] ?></textarea> -->
                      <input type="text" list="<?= $dataBaseName ?>-datalist" class="mdl-textfield__input <?= $dataBaseName ?>" value="<?= $mold[$dataBaseName] ?>" autocomplete="off" name="<?= $dataBaseName ?>">
                      <datalist id="<?= $dataBaseName ?>-datalist">
                        <?php foreach ($refSpecs as $spec) : ?>
                          <option value="<?= $spec['REF_SPEC'] ?>"><?= $spec['REF_SPEC'] ?></option>
                        <?php endforeach; ?>
                      </datalist>
                      <label class="mdl-textfield__label"><?= $this->getVerifyTranslate($translateData, $data['name']) ?></label>
                    </div>
                    <?php break; ?>
                  <?php
                        case 'CODE_PROD_2': ?>
                    <div id="<?= $dataBaseName ?>" class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-cell mdl-cell--6-col">
                      <!-- <textarea class="mdl-textfield__input" type="text" rows="3" name="<?= $dataBaseName ?>"><?= $mold[$dataBaseName] ?></textarea> -->
                      <input type="text" class="mdl-textfield__input <?= $dataBaseName ?>" value="<?= $mold[$dataBaseName] ?>" disabled style="color: rgb(96,125,139);">
                      <input type="hidden" class="<?= $dataBaseName ?>" name="<?= $dataBaseName ?>" value="<?= $mold[$dataBaseName] ?>">
                      <label class="mdl-textfield__label"><?= $this->getVerifyTranslate($translateData, $data['name']) ?></label>
                    </div>
                    <?php break; ?>
                  <?php endswitch; ?>
                <?php endif; ?>
              <?php endforeach; ?>
          </div>
        </div>
      </div>
    <?php endforeach; ?>
  </form>

  <!-- Confirmation du formulaire -->
  <div class="mdl-card__actions mdl-card--border">
    <button id="button_edit_form" class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-color--green mdl-color-text--white right">
      <?= $this->getVerifyTranslate($translate, 'buttonEditMold') ?>
    </button>
    <div class="mdl-tooltip" for="button_edit_form"><?= $this->getVerifyTranslate($translate, 'buttonEditMold') ?></div>
    <button id="close_edit_form_button" data-id=<?= $dataID ?> class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-color--red mdl-color-text--white close">
      <?= $this->getVerifyTranslate($translate, 'buttonCancel') ?>
    </button>
    <div class="mdl-tooltip" for="close_edit_form_button"><?= $this->getVerifyTranslate($translate, 'buttonCancel') ?></div>
  </div>

  <!-- Fermeture du formulaire -->
  <div class="mdl-card__menu">
    <button id="close_edit_form" data-id=<?= $dataID ?> class="mdl-button mdl-js-button mdl-js-ripple-effect mdl-button--icon mdl-color-text--white close">
      <i class="material-icons">close</i>
    </button>
    <div class="mdl-tooltip" for="close_edit_form"><?= $this->getVerifyTranslate($translate, 'buttonCancel') ?></div>
  </div>
</div>



<!-- Ajout des descriptions pour chaque champs -->
<?php foreach ($dataList as $dataBaseName => $data) : ?>
  <div class="mdl-tooltip mdl-tooltip--large" for="<?= $dataBaseName ?>"><?= $this->getVerifyTranslate($translateData, $data['description']) ?></div>
<?php endforeach; ?>



<!-- Script JavaScript -->
<script type="text/javascript">
  // Fermeture du formulaire
  document.querySelectorAll('.close').forEach(function(button) {
    button.addEventListener('click', function() {
      window.location.replace('/mold/advancedView/' + button.dataset.id);
    });
  });

  // Confirmation du formulaire
  document.querySelector('#button_edit_form').addEventListener('click', function() {
    var form = document.querySelector('#edit_form');

    if (form.reportValidity())
      form.submit();
  });

  let refSpecs = document.querySelector('.REF_SPECS');
  let inputCodes = document.querySelectorAll('.CODE_PROD_2');

  if (refSpecs != undefined && inputCodes != undefined) {
    refSpecs.addEventListener('input', function() {
      console.log(refSpecs.value);
      if (refSpecs.value != '') {
        $http('/mold/getCodes/' + refSpecs.value)
          .get()
          .then(function(data) {
            data = data.replace(/\"/g, '');
            inputCodes.forEach(function(code) {
              code.value = data;
              if (code.parentNode.MaterialTextfield != undefined) {
                code.parentNode.MaterialTextfield.checkDirty();
              }
            })
          })
      } else {
        inputCodes.forEach(function(code) {
          code.value = '';
          if (code.parentNode.MaterialTextfield != undefined) {
            code.parentNode.MaterialTextfield.checkDirty();
          }
        })
      }
    })
  }
</script>