--------------------------------------------------------
--  DDL for Table MOLD_USERS
--------------------------------------------------------

  CREATE TABLE "AS_MOULES"."MOLD_USERS" 
   (	"USERID" VARCHAR2(15 BYTE), 
	"NOMPRE" VARCHAR2(40 BYTE), 
	"PASSWORD" VARCHAR2(40 BYTE), 
	"MAIN_RULE" CLOB, 
	"DATA_RULE" CLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AS_MOULES" 
 LOB ("MAIN_RULE") STORE AS BASICFILE (
  TABLESPACE "AS_MOULES" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("DATA_RULE") STORE AS BASICFILE (
  TABLESPACE "AS_MOULES" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
REM INSERTING into AS_MOULES.MOLD_USERS
SET DEFINE OFF;
Insert into AS_MOULES.MOLD_USERS (USERID,NOMPRE,PASSWORD) values ('ADMIN42','IT MoldGod','61bc49d6e37a7626db667e1144bd3e22b4c2d353','{"admin":true}','{"Mold_App":{"STATUS_MOULE":{"edit":true,"search":true,"primary":true},"REF_MOULE":{"edit":true,"search":true,"primary":true},"PATTERNSIZE":{"edit":true,"search":true,"primary":true},"CODE_PROD_2":{"edit":true,"search":true,"primary":true},"REF_DIMENSION":{"edit":true},"DIM_CTN2":{"edit":true}}}');
--------------------------------------------------------
--  DDL for Index MOLD_USERS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AS_MOULES"."MOLD_USERS_PK" ON "AS_MOULES"."MOLD_USERS" ("USERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AS_MOULES" ;
--------------------------------------------------------
--  Constraints for Table MOLD_USERS
--------------------------------------------------------

  ALTER TABLE "AS_MOULES"."MOLD_USERS" ADD CONSTRAINT "MOLD_USERS_PK" PRIMARY KEY ("USERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AS_MOULES"  ENABLE;
  ALTER TABLE "AS_MOULES"."MOLD_USERS" MODIFY ("DATA_RULE" NOT NULL ENABLE);
  ALTER TABLE "AS_MOULES"."MOLD_USERS" MODIFY ("MAIN_RULE" NOT NULL ENABLE);
  ALTER TABLE "AS_MOULES"."MOLD_USERS" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "AS_MOULES"."MOLD_USERS" MODIFY ("NOMPRE" NOT NULL ENABLE);
  ALTER TABLE "AS_MOULES"."MOLD_USERS" MODIFY ("USERID" NOT NULL ENABLE);





--------------------------------------------------------
--  DDL for Table MOLD_DATA_CATEGORY_TYPE
--------------------------------------------------------

  CREATE TABLE "AS_MOULES"."MOLD_DATA_CATEGORY_TYPE" 
   (	"ID" NUMBER, 
	"TYPE" VARCHAR2(40 BYTE), 
	"COLOR" VARCHAR2(6 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AS_MOULES" ;
REM INSERTING into AS_MOULES.MOLD_DATA_CATEGORY_TYPE
SET DEFINE OFF;
Insert into AS_MOULES.MOLD_DATA_CATEGORY_TYPE (ID,TYPE,COLOR) values ('1','mainName','60a3bc');
Insert into AS_MOULES.MOLD_DATA_CATEGORY_TYPE (ID,TYPE,COLOR) values ('2','qualityName','78e08f');
Insert into AS_MOULES.MOLD_DATA_CATEGORY_TYPE (ID,TYPE,COLOR) values ('3','metroName','079992');
Insert into AS_MOULES.MOLD_DATA_CATEGORY_TYPE (ID,TYPE,COLOR) values ('4','exceptName','f8c291');
Insert into AS_MOULES.MOLD_DATA_CATEGORY_TYPE (ID,TYPE,COLOR) values ('5','infoName','f6b93b');
Insert into AS_MOULES.MOLD_DATA_CATEGORY_TYPE (ID,TYPE,COLOR) values ('6','productName','1e3799');
Insert into AS_MOULES.MOLD_DATA_CATEGORY_TYPE (ID,TYPE,COLOR) values ('7','controlName','b71540');
Insert into AS_MOULES.MOLD_DATA_CATEGORY_TYPE (ID,TYPE,COLOR) values ('8','techInfoName','6a89cc');
--------------------------------------------------------
--  DDL for Index MOLD_DATA_CATEGORY_TYPE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AS_MOULES"."MOLD_DATA_CATEGORY_TYPE_PK" ON "AS_MOULES"."MOLD_DATA_CATEGORY_TYPE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AS_MOULES" ;
--------------------------------------------------------
--  DDL for Trigger MOLD_DATA_CATEGORY_TYPE_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "AS_MOULES"."MOLD_DATA_CATEGORY_TYPE_TRG" 
BEFORE INSERT ON MOLD_DATA_CATEGORY_TYPE 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT MOLD_DATA_CATEGORY_TYPE_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "AS_MOULES"."MOLD_DATA_CATEGORY_TYPE_TRG" ENABLE;
--------------------------------------------------------
--  Constraints for Table MOLD_DATA_CATEGORY_TYPE
--------------------------------------------------------

  ALTER TABLE "AS_MOULES"."MOLD_DATA_CATEGORY_TYPE" ADD CONSTRAINT "MOLD_DATA_CATEGORY_TYPE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AS_MOULES"  ENABLE;
  ALTER TABLE "AS_MOULES"."MOLD_DATA_CATEGORY_TYPE" MODIFY ("COLOR" NOT NULL ENABLE);
  ALTER TABLE "AS_MOULES"."MOLD_DATA_CATEGORY_TYPE" MODIFY ("TYPE" NOT NULL ENABLE);
  ALTER TABLE "AS_MOULES"."MOLD_DATA_CATEGORY_TYPE" MODIFY ("ID" NOT NULL ENABLE);





--------------------------------------------------------
--  DDL for Table MOLD_DATA_LIST
--------------------------------------------------------

  CREATE TABLE "AS_MOULES"."MOLD_DATA_LIST" 
   (	"ID" NUMBER, 
	"APP" VARCHAR2(20 BYTE), 
	"CATEGORY" NUMBER, 
	"BASE_NAME" VARCHAR2(40 BYTE), 
	"NAME" VARCHAR2(60 BYTE), 
	"DESCRIPTION" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AS_MOULES" ;
REM INSERTING into AS_MOULES.MOLD_DATA_LIST
SET DEFINE OFF;
Insert into AS_MOULES.MOLD_DATA_LIST (ID,APP,CATEGORY,BASE_NAME,NAME,DESCRIPTION) values ('1','Mold_App','1','STATUT','statutName','statutDescription');
Insert into AS_MOULES.MOLD_DATA_LIST (ID,APP,CATEGORY,BASE_NAME,NAME,DESCRIPTION) values ('2','Mold_App','1','LOCATION_TYPE','locationTypeName','locationTypeDescription');
Insert into AS_MOULES.MOLD_DATA_LIST (ID,APP,CATEGORY,BASE_NAME,NAME,DESCRIPTION) values ('3','Mold_App','1','LOCATION','locationName','locationDescription');
Insert into AS_MOULES.MOLD_DATA_LIST (ID,APP,CATEGORY,BASE_NAME,NAME,DESCRIPTION) values ('4','Mold_App','1','REF_MOULE','refMouleName','refMouleDescription');
Insert into AS_MOULES.MOLD_DATA_LIST (ID,APP,CATEGORY,BASE_NAME,NAME,DESCRIPTION) values ('5','Mold_App','3','LAST_CHECK_DATE','lastCheckDateName','lastCheckDateDescription');
Insert into AS_MOULES.MOLD_DATA_LIST (ID,APP,CATEGORY,BASE_NAME,NAME,DESCRIPTION) values ('6','Mold_App','3','LAST_RESULT','lastResultName','lastResultDescription');
Insert into AS_MOULES.MOLD_DATA_LIST (ID,APP,CATEGORY,BASE_NAME,NAME,DESCRIPTION) values ('7','Mold_App','3','COMMENT_METRO','commentMetroName','commentMetroDescription');
Insert into AS_MOULES.MOLD_DATA_LIST (ID,APP,CATEGORY,BASE_NAME,NAME,DESCRIPTION) values ('8','Mold_App','4','START_DATE','startDateName','startDateDescription');
Insert into AS_MOULES.MOLD_DATA_LIST (ID,APP,CATEGORY,BASE_NAME,NAME,DESCRIPTION) values ('9','Mold_App','4','END_DATE','endDateName','endDateDescription');
Insert into AS_MOULES.MOLD_DATA_LIST (ID,APP,CATEGORY,BASE_NAME,NAME,DESCRIPTION) values ('10','Mold_App','4','COMMENT_EXCEPT','commentExceptName','commentExceptDescription');
Insert into AS_MOULES.MOLD_DATA_LIST (ID,APP,CATEGORY,BASE_NAME,NAME,DESCRIPTION) values ('11','Mold_App','5','COMMENTAIRE','commentaireName','commentaireDescription');
Insert into AS_MOULES.MOLD_DATA_LIST (ID,APP,CATEGORY,BASE_NAME,NAME,DESCRIPTION) values ('12','Mold_App','1','PATTERNSIZE','patternsizeName','patternsizeDescription');
Insert into AS_MOULES.MOLD_DATA_LIST (ID,APP,CATEGORY,BASE_NAME,NAME,DESCRIPTION) values ('13','Mold_App','6','CODE_PROD_2','codeProd2Name','codeProd2Description');
Insert into AS_MOULES.MOLD_DATA_LIST (ID,APP,CATEGORY,BASE_NAME,NAME,DESCRIPTION) values ('14','Mold_App','7','NB_CYCLE_CUISSON_LIFE','nbCycleCuissonLifeName','nbCycleCuissonLifeDescription');
Insert into AS_MOULES.MOLD_DATA_LIST (ID,APP,CATEGORY,BASE_NAME,NAME,DESCRIPTION) values ('15','Mold_App','7','NB_CYCLE_CUISSON_NOW','nbCycleCuissonNowName','nbCycleCuissonNowDescription');
Insert into AS_MOULES.MOLD_DATA_LIST (ID,APP,CATEGORY,BASE_NAME,NAME,DESCRIPTION) values ('16','Mold_App','8','DIM_CTN2','dimCTN2Name','dimCTN2Description');
Insert into AS_MOULES.MOLD_DATA_LIST (ID,APP,CATEGORY,BASE_NAME,NAME,DESCRIPTION) values ('17','Mold_App','8','GOUPILLE2','goupille2Name','goupille2Description');
Insert into AS_MOULES.MOLD_DATA_LIST (ID,APP,CATEGORY,BASE_NAME,NAME,DESCRIPTION) values ('18','Mold_App','8','REF_CTN','refCTNName','refCTNDescription');
Insert into AS_MOULES.MOLD_DATA_LIST (ID,APP,CATEGORY,BASE_NAME,NAME,DESCRIPTION) values ('19','Mold_App','8','REF_SEGMENT','refSegmentName','refSegmentDescription');
Insert into AS_MOULES.MOLD_DATA_LIST (ID,APP,CATEGORY,BASE_NAME,NAME,DESCRIPTION) values ('20','Mold_App','8','REF_FLANC_SUP','refFlancSupName','refFlancSupDescription');
Insert into AS_MOULES.MOLD_DATA_LIST (ID,APP,CATEGORY,BASE_NAME,NAME,DESCRIPTION) values ('21','Mold_App','8','REF_FLANC_INF','refFlancInfName','refFlancInfDescription');
Insert into AS_MOULES.MOLD_DATA_LIST (ID,APP,CATEGORY,BASE_NAME,NAME,DESCRIPTION) values ('22','Mold_App','8','DATE_GET_MOLD','dateGetMoldName','dateGetMoldDescription');
Insert into AS_MOULES.MOLD_DATA_LIST (ID,APP,CATEGORY,BASE_NAME,NAME,DESCRIPTION) values ('23','Mold_App','8','TYPE_CTN2','typeCTN2Name','typeCTN2Description');
Insert into AS_MOULES.MOLD_DATA_LIST (ID,APP,CATEGORY,BASE_NAME,NAME,DESCRIPTION) values ('24','Mold_App','1','POSITION_ACTUEL_DATE','positionActuelDateName','positionActuelDateDescription');
Insert into AS_MOULES.MOLD_DATA_LIST (ID,APP,CATEGORY,BASE_NAME,NAME,DESCRIPTION) values ('25','Mold_App','8','GSWR_BOTTOM','GSWRBottomName','GSWRBottomDescription');
Insert into AS_MOULES.MOLD_DATA_LIST (ID,APP,CATEGORY,BASE_NAME,NAME,DESCRIPTION) values ('26','Mold_App','8','GSWR_TOP','GSWRTopName','GSWRTopDescription');
Insert into AS_MOULES.MOLD_DATA_LIST (ID,APP,CATEGORY,BASE_NAME,NAME,DESCRIPTION) values ('27','Mold_App','8','GTRD','GTRDName','GTRDDescription');
Insert into AS_MOULES.MOLD_DATA_LIST (ID,APP,CATEGORY,BASE_NAME,NAME,DESCRIPTION) values ('28','Mold_App','8','DRAWING','drawingName','drawingDescription');
Insert into AS_MOULES.MOLD_DATA_LIST (ID,APP,CATEGORY,BASE_NAME,NAME,DESCRIPTION) values ('29','Mold_App','8','S_DIAMETRE','sDiametreName','sDiametreDescription');
Insert into AS_MOULES.MOLD_DATA_LIST (ID,APP,CATEGORY,BASE_NAME,NAME,DESCRIPTION) values ('30','Mold_App','8','L_DIAMETRE','lDiametreName','lDiametreDescription');
Insert into AS_MOULES.MOLD_DATA_LIST (ID,APP,CATEGORY,BASE_NAME,NAME,DESCRIPTION) values ('31','Mold_App','8','JEUX_TOTAL_SECTEUR','jeuxTotalSecteurName','jeuxTotalSecteurDescription');
Insert into AS_MOULES.MOLD_DATA_LIST (ID,APP,CATEGORY,BASE_NAME,NAME,DESCRIPTION) values ('32','Mold_App','8','CLOGGED_HOLES','cloggedHolesName','cloggedHolesDescription');
Insert into AS_MOULES.MOLD_DATA_LIST (ID,APP,CATEGORY,BASE_NAME,NAME,DESCRIPTION) values ('33','Mold_App','2','DATE_LAST_ENVELOPPE','dateLastEnveloppeName','dateLastEnveloppeDescription');
Insert into AS_MOULES.MOLD_DATA_LIST (ID,APP,CATEGORY,BASE_NAME,NAME,DESCRIPTION) values ('34','Mold_App','2','GRADES','gradesName','gradesDescription');
Insert into AS_MOULES.MOLD_DATA_LIST (ID,APP,CATEGORY,BASE_NAME,NAME,DESCRIPTION) values ('35','Mold_App','2','CAUSE_GRADE','causeGradeName','causeGradeDescription');
Insert into AS_MOULES.MOLD_DATA_LIST (ID,APP,CATEGORY,BASE_NAME,NAME,DESCRIPTION) values ('36','Code_App','1','STATUS','statusCodeName','statusCodeDescription');
Insert into AS_MOULES.MOLD_DATA_LIST (ID,APP,CATEGORY,BASE_NAME,NAME,DESCRIPTION) values ('37','Code_App','1','CODE_PROD_1','codeProd1Name','codeProd1Description');
Insert into AS_MOULES.MOLD_DATA_LIST (ID,APP,CATEGORY,BASE_NAME,NAME,DESCRIPTION) values ('38','Code_App','1','S_DIA_RELIEVE','sDiaRelieveName','sDiaRelieveDescription');
Insert into AS_MOULES.MOLD_DATA_LIST (ID,APP,CATEGORY,BASE_NAME,NAME,DESCRIPTION) values ('39','Code_App','7','SEUIL_CRYO_CODE','seuilCryoCodeName','seuilCryoCodeDescription');
Insert into AS_MOULES.MOLD_DATA_LIST (ID,APP,CATEGORY,BASE_NAME,NAME,DESCRIPTION) values ('40','Code_App','8','N_SPEC_EQUIP','nSpecEquipName','nSpecEquipDescription');
Insert into AS_MOULES.MOLD_DATA_LIST (ID,APP,CATEGORY,BASE_NAME,NAME,DESCRIPTION) values ('41','Code_App','1','CODE_PROFIL','codeProfilName','codeProfilDescription');
Insert into AS_MOULES.MOLD_DATA_LIST (ID,APP,CATEGORY,BASE_NAME,NAME,DESCRIPTION) values ('42','Code_App','6','SALES_CODE','salesCodeName','salesCodeDescription');
Insert into AS_MOULES.MOLD_DATA_LIST (ID,APP,CATEGORY,BASE_NAME,NAME,DESCRIPTION) values ('43','Code_App','8','BAGUES_TYPE','baguesTypeName','baguesTypeDescription');
Insert into AS_MOULES.MOLD_DATA_LIST (ID,APP,CATEGORY,BASE_NAME,NAME,DESCRIPTION) values ('44','Code_App','7','SMARTEAM','smarteamName','smarteamDescription');
Insert into AS_MOULES.MOLD_DATA_LIST (ID,APP,CATEGORY,BASE_NAME,NAME,DESCRIPTION) values ('45','Code_App','8','GOUPILLE','goupilleName','goupilleDescription');
Insert into AS_MOULES.MOLD_DATA_LIST (ID,APP,CATEGORY,BASE_NAME,NAME,DESCRIPTION) values ('46','Code_App','8','BAGO_BMR','bagoBMRName','bagoBMRDescription');
Insert into AS_MOULES.MOLD_DATA_LIST (ID,APP,CATEGORY,BASE_NAME,NAME,DESCRIPTION) values ('47','Code_App','8','BAGO_TMR','bagoTMRName','bagoTMRDescription');
Insert into AS_MOULES.MOLD_DATA_LIST (ID,APP,CATEGORY,BASE_NAME,NAME,DESCRIPTION) values ('48','Code_App','8','BAGO_ADAPTER','bagoAdapterName','bagoAdapterDescription');
Insert into AS_MOULES.MOLD_DATA_LIST (ID,APP,CATEGORY,BASE_NAME,NAME,DESCRIPTION) values ('49','Code_App','8','BAGO_BLADDER','bagoBladderName','bagoBladderDescription');
Insert into AS_MOULES.MOLD_DATA_LIST (ID,APP,CATEGORY,BASE_NAME,NAME,DESCRIPTION) values ('50','Code_App','8','MHI_BMR','mhiBMRName','mhiBMRDescription');
Insert into AS_MOULES.MOLD_DATA_LIST (ID,APP,CATEGORY,BASE_NAME,NAME,DESCRIPTION) values ('51','Code_App','8','MHI_BLADDER','mhiBladderName','mhiBladderDescription');
Insert into AS_MOULES.MOLD_DATA_LIST (ID,APP,CATEGORY,BASE_NAME,NAME,DESCRIPTION) values ('52','Code_App','8','T_MINI','tMiniName','tMiniDescription');
Insert into AS_MOULES.MOLD_DATA_LIST (ID,APP,CATEGORY,BASE_NAME,NAME,DESCRIPTION) values ('53','Code_App','8','T_MAXI','tMaxiName','tMaxiDescription');
Insert into AS_MOULES.MOLD_DATA_LIST (ID,APP,CATEGORY,BASE_NAME,NAME,DESCRIPTION) values ('54','Code_App','8','PCI','pciName','pciDescription');
Insert into AS_MOULES.MOLD_DATA_LIST (ID,APP,CATEGORY,BASE_NAME,NAME,DESCRIPTION) values ('55','Code_App','8','S_DIAMETRE','sDiametreName','sDiametreDescription');
Insert into AS_MOULES.MOLD_DATA_LIST (ID,APP,CATEGORY,BASE_NAME,NAME,DESCRIPTION) values ('56','Code_App','8','L_DIAMETRE','lDiametreName','lDiametreDescription');
Insert into AS_MOULES.MOLD_DATA_LIST (ID,APP,CATEGORY,BASE_NAME,NAME,DESCRIPTION) values ('57','Code_App','8','JEUX_TOTAL_SECTEUR','jeuxTotalSecteurName','jeuxTotalSecteurDescription');
Insert into AS_MOULES.MOLD_DATA_LIST (ID,APP,CATEGORY,BASE_NAME,NAME,DESCRIPTION) values ('58','Code_App','1','REF_SPEC','refSpecName','refSpecDescription');
Insert into AS_MOULES.MOLD_DATA_LIST (ID,APP,CATEGORY,BASE_NAME,NAME,DESCRIPTION) values ('59','Code_App','8','TYPE_PRESSE','typePresseName','typePresseDescription');
--------------------------------------------------------
--  DDL for Index MOLD_DATA_LIST_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AS_MOULES"."MOLD_DATA_LIST_PK" ON "AS_MOULES"."MOLD_DATA_LIST" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AS_MOULES" ;
--------------------------------------------------------
--  DDL for Trigger MOLD_DATA_LIST_TRG01
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "AS_MOULES"."MOLD_DATA_LIST_TRG01" 
BEFORE INSERT ON MOLD_DATA_LIST 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT MOLD_DATA_LIST_SEQ01.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "AS_MOULES"."MOLD_DATA_LIST_TRG01" ENABLE;
--------------------------------------------------------
--  Constraints for Table MOLD_DATA_LIST
--------------------------------------------------------

  ALTER TABLE "AS_MOULES"."MOLD_DATA_LIST" ADD CONSTRAINT "MOLD_DATA_LIST_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AS_MOULES"  ENABLE;
  ALTER TABLE "AS_MOULES"."MOLD_DATA_LIST" MODIFY ("DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "AS_MOULES"."MOLD_DATA_LIST" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "AS_MOULES"."MOLD_DATA_LIST" MODIFY ("BASE_NAME" NOT NULL ENABLE);
  ALTER TABLE "AS_MOULES"."MOLD_DATA_LIST" MODIFY ("CATEGORY" NOT NULL ENABLE);
  ALTER TABLE "AS_MOULES"."MOLD_DATA_LIST" MODIFY ("APP" NOT NULL ENABLE);
  ALTER TABLE "AS_MOULES"."MOLD_DATA_LIST" MODIFY ("ID" NOT NULL ENABLE);





--------------------------------------------------------
--  DDL for Table MOLD_HISTORY_TYPE
--------------------------------------------------------

  CREATE TABLE "AS_MOULES"."MOLD_HISTORY_TYPE" 
   (	"ID" NUMBER, 
	"TYPE" VARCHAR2(40 BYTE), 
	"COLOR" VARCHAR2(6 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AS_MOULES" ;
REM INSERTING into AS_MOULES.MOLD_HISTORY_TYPE
SET DEFINE OFF;
Insert into AS_MOULES.MOLD_HISTORY_TYPE (ID,TYPE,COLOR) values ('1','insert','78e08f');
Insert into AS_MOULES.MOLD_HISTORY_TYPE (ID,TYPE,COLOR) values ('2','update','60a3bc');
Insert into AS_MOULES.MOLD_HISTORY_TYPE (ID,TYPE,COLOR) values ('3','delete','eb2f06');
--------------------------------------------------------
--  DDL for Index MOLD_HISTORY_TYPE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AS_MOULES"."MOLD_HISTORY_TYPE_PK" ON "AS_MOULES"."MOLD_HISTORY_TYPE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AS_MOULES" ;
--------------------------------------------------------
--  DDL for Trigger MOLD_HISTORY_TYPE_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "AS_MOULES"."MOLD_HISTORY_TYPE_TRG" 
BEFORE INSERT ON MOLD_HISTORY_TYPE 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "AS_MOULES"."MOLD_HISTORY_TYPE_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger MOLD_HISTORY_TYPE_TRG1
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "AS_MOULES"."MOLD_HISTORY_TYPE_TRG1" 
BEFORE INSERT ON MOLD_HISTORY_TYPE 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT MOLD_HISTORY_TYPE_SEQ2.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "AS_MOULES"."MOLD_HISTORY_TYPE_TRG1" ENABLE;
--------------------------------------------------------
--  Constraints for Table MOLD_HISTORY_TYPE
--------------------------------------------------------

  ALTER TABLE "AS_MOULES"."MOLD_HISTORY_TYPE" MODIFY ("COLOR" NOT NULL ENABLE);
  ALTER TABLE "AS_MOULES"."MOLD_HISTORY_TYPE" ADD CONSTRAINT "MOLD_HISTORY_TYPE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AS_MOULES"  ENABLE;
  ALTER TABLE "AS_MOULES"."MOLD_HISTORY_TYPE" MODIFY ("TYPE" NOT NULL ENABLE);
  ALTER TABLE "AS_MOULES"."MOLD_HISTORY_TYPE" MODIFY ("ID" NOT NULL ENABLE);





--------------------------------------------------------
--  DDL for Table MOLD_HISTORY
--------------------------------------------------------

  CREATE TABLE "AS_MOULES"."MOLD_HISTORY" 
   (	"ID" NUMBER, 
	"APP" VARCHAR2(20 BYTE), 
	"ID_DATA" VARCHAR2(15 BYTE), 
	"DATETIME" DATE, 
	"HISTORY_TYPE" NUMBER, 
	"DATA_BASE_NAME" VARCHAR2(40 BYTE), 
	"NEW_VALUE" VARCHAR2(200 BYTE), 
	"USERID" VARCHAR2(15 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AS_MOULES" ;
REM INSERTING into AS_MOULES.MOLD_HISTORY
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index MOLD_HISTORY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AS_MOULES"."MOLD_HISTORY_PK" ON "AS_MOULES"."MOLD_HISTORY" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AS_MOULES" ;
--------------------------------------------------------
--  DDL for Trigger MOLD_HISTORY_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "AS_MOULES"."MOLD_HISTORY_TRG" 
BEFORE INSERT ON MOLD_HISTORY 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT MOLD_HISTORY_SEQ4.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "AS_MOULES"."MOLD_HISTORY_TRG" ENABLE;
--------------------------------------------------------
--  Constraints for Table MOLD_HISTORY
--------------------------------------------------------

  ALTER TABLE "AS_MOULES"."MOLD_HISTORY" ADD CONSTRAINT "MOLD_HISTORY_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AS_MOULES"  ENABLE;
  ALTER TABLE "AS_MOULES"."MOLD_HISTORY" MODIFY ("USERID" NOT NULL ENABLE);
  ALTER TABLE "AS_MOULES"."MOLD_HISTORY" MODIFY ("DATA_BASE_NAME" NOT NULL ENABLE);
  ALTER TABLE "AS_MOULES"."MOLD_HISTORY" MODIFY ("HISTORY_TYPE" NOT NULL ENABLE);
  ALTER TABLE "AS_MOULES"."MOLD_HISTORY" MODIFY ("DATETIME" NOT NULL ENABLE);
  ALTER TABLE "AS_MOULES"."MOLD_HISTORY" MODIFY ("ID_DATA" NOT NULL ENABLE);
  ALTER TABLE "AS_MOULES"."MOLD_HISTORY" MODIFY ("APP" NOT NULL ENABLE);
  ALTER TABLE "AS_MOULES"."MOLD_HISTORY" MODIFY ("ID" NOT NULL ENABLE);





--------------------------------------------------------
--  DDL for Table MOLD_STATUS_TYPE
--------------------------------------------------------

  CREATE TABLE "AS_MOULES"."MOLD_STATUS_TYPE" 
   (	"ID" NUMBER, 
	"TYPE" VARCHAR2(40 BYTE), 
	"COLOR" VARCHAR2(6 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AS_MOULES" ;
REM INSERTING into AS_MOULES.MOLD_STATUS_TYPE
SET DEFINE OFF;
Insert into AS_MOULES.MOLD_STATUS_TYPE (ID,TYPE,COLOR) values ('1','operationnelName','78e08f');
Insert into AS_MOULES.MOLD_STATUS_TYPE (ID,TYPE,COLOR) values ('2','onPresseName','f6b93b');
Insert into AS_MOULES.MOLD_STATUS_TYPE (ID,TYPE,COLOR) values ('3','onDerogationName','b71540');
Insert into AS_MOULES.MOLD_STATUS_TYPE (ID,TYPE,COLOR) values ('4','newName','fad390');
Insert into AS_MOULES.MOLD_STATUS_TYPE (ID,TYPE,COLOR) values ('5','toCleaningName','0a3d62');
Insert into AS_MOULES.MOLD_STATUS_TYPE (ID,TYPE,COLOR) values ('6','toFixingName','e55039');
Insert into AS_MOULES.MOLD_STATUS_TYPE (ID,TYPE,COLOR) values ('7','toControlName','0c2461');
Insert into AS_MOULES.MOLD_STATUS_TYPE (ID,TYPE,COLOR) values ('8','toDeleteName','fa983a');
Insert into AS_MOULES.MOLD_STATUS_TYPE (ID,TYPE,COLOR) values ('9','inCleaningName','82ccdd');
Insert into AS_MOULES.MOLD_STATUS_TYPE (ID,TYPE,COLOR) values ('10','inFixingName','f8c291');
Insert into AS_MOULES.MOLD_STATUS_TYPE (ID,TYPE,COLOR) values ('11','inControlName','6a89cc');
Insert into AS_MOULES.MOLD_STATUS_TYPE (ID,TYPE,COLOR) values ('12','trousBouchesName','b71540');
Insert into AS_MOULES.MOLD_STATUS_TYPE (ID,TYPE,COLOR) values ('13','deleteName','eb2f06');
Insert into AS_MOULES.MOLD_STATUS_TYPE (ID,TYPE,COLOR) values ('14','transfertName','e58e26');
Insert into AS_MOULES.MOLD_STATUS_TYPE (ID,TYPE,COLOR) values ('15','waitingDerogationName','4a69bd');
Insert into AS_MOULES.MOLD_STATUS_TYPE (ID,TYPE,COLOR) values ('16','waitingReceptionName','3c6382');
Insert into AS_MOULES.MOLD_STATUS_TYPE (ID,TYPE,COLOR) values ('17','fixingReturnName','38ada9');
--------------------------------------------------------
--  DDL for Index MOLD_STATUS_TYPE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AS_MOULES"."MOLD_STATUS_TYPE_PK" ON "AS_MOULES"."MOLD_STATUS_TYPE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AS_MOULES" ;
--------------------------------------------------------
--  DDL for Trigger MOLD_STATUS_TYPE_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "AS_MOULES"."MOLD_STATUS_TYPE_TRG" 
BEFORE INSERT ON MOLD_STATUS_TYPE 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "AS_MOULES"."MOLD_STATUS_TYPE_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger MOLD_STATUS_TYPE_TRG1
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "AS_MOULES"."MOLD_STATUS_TYPE_TRG1" 
BEFORE INSERT ON MOLD_STATUS_TYPE 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT MOLD_STATUS_TYPE_SEQ2.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "AS_MOULES"."MOLD_STATUS_TYPE_TRG1" ENABLE;
--------------------------------------------------------
--  Constraints for Table MOLD_STATUS_TYPE
--------------------------------------------------------

  ALTER TABLE "AS_MOULES"."MOLD_STATUS_TYPE" MODIFY ("COLOR" NOT NULL ENABLE);
  ALTER TABLE "AS_MOULES"."MOLD_STATUS_TYPE" ADD CONSTRAINT "MOLD_STATUS_TYPE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AS_MOULES"  ENABLE;
  ALTER TABLE "AS_MOULES"."MOLD_STATUS_TYPE" MODIFY ("TYPE" NOT NULL ENABLE);
  ALTER TABLE "AS_MOULES"."MOLD_STATUS_TYPE" MODIFY ("ID" NOT NULL ENABLE);





--------------------------------------------------------
--  DDL for Table MOLD_LOCATION_TYPE
--------------------------------------------------------

  CREATE TABLE "AS_MOULES"."MOLD_LOCATION_TYPE" 
   (	"ID" NUMBER, 
	"TYPE" VARCHAR2(40 BYTE), 
	"COLOR" VARCHAR2(6 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AS_MOULES" ;
REM INSERTING into AS_MOULES.MOLD_LOCATION_TYPE
SET DEFINE OFF;
Insert into AS_MOULES.MOLD_LOCATION_TYPE (ID,TYPE,COLOR) values ('1','storageName','38ada9');
Insert into AS_MOULES.MOLD_LOCATION_TYPE (ID,TYPE,COLOR) values ('2','horsUsineName','0c2461');
Insert into AS_MOULES.MOLD_LOCATION_TYPE (ID,TYPE,COLOR) values ('3','sousTerreName','eb2f06');
Insert into AS_MOULES.MOLD_LOCATION_TYPE (ID,TYPE,COLOR) values ('4','presseName','82ccdd');
Insert into AS_MOULES.MOLD_LOCATION_TYPE (ID,TYPE,COLOR) values ('5','metrologyName','78e08f');
Insert into AS_MOULES.MOLD_LOCATION_TYPE (ID,TYPE,COLOR) values ('6','qualityName','1e3799');
Insert into AS_MOULES.MOLD_LOCATION_TYPE (ID,TYPE,COLOR) values ('7','LKYName','6a89cc');
--------------------------------------------------------
--  DDL for Index MOLD_LOCATION_TYPE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AS_MOULES"."MOLD_LOCATION_TYPE_PK" ON "AS_MOULES"."MOLD_LOCATION_TYPE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AS_MOULES" ;
--------------------------------------------------------
--  DDL for Trigger MOLD_LOCATION_TYPE_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "AS_MOULES"."MOLD_LOCATION_TYPE_TRG" 
BEFORE INSERT ON MOLD_LOCATION_TYPE 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "AS_MOULES"."MOLD_LOCATION_TYPE_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger MOLD_LOCATION_TYPE_TRG1
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "AS_MOULES"."MOLD_LOCATION_TYPE_TRG1" 
BEFORE INSERT ON MOLD_LOCATION_TYPE 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT MOLD_LOCATION_TYPE_SEQ2.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "AS_MOULES"."MOLD_LOCATION_TYPE_TRG1" ENABLE;
--------------------------------------------------------
--  Constraints for Table MOLD_LOCATION_TYPE
--------------------------------------------------------

  ALTER TABLE "AS_MOULES"."MOLD_LOCATION_TYPE" MODIFY ("COLOR" NOT NULL ENABLE);
  ALTER TABLE "AS_MOULES"."MOLD_LOCATION_TYPE" ADD CONSTRAINT "MOLD_LOCATION_TYPE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AS_MOULES"  ENABLE;
  ALTER TABLE "AS_MOULES"."MOLD_LOCATION_TYPE" MODIFY ("TYPE" NOT NULL ENABLE);
  ALTER TABLE "AS_MOULES"."MOLD_LOCATION_TYPE" MODIFY ("ID" NOT NULL ENABLE);





--------------------------------------------------------
--  DDL for Table MOLD_STATUS
--------------------------------------------------------

  CREATE TABLE "AS_MOULES"."MOLD_STATUS" 
   (	"ID_MOLD" VARCHAR2(15 BYTE), 
	"STATUS_TYPE" NUMBER, 
	"LOCATION_TYPE" NUMBER, 
	"LOCATION" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AS_MOULES" ;
REM INSERTING into AS_MOULES.MOLD_STATUS
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index MOLD_STATUS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AS_MOULES"."MOLD_STATUS_PK" ON "AS_MOULES"."MOLD_STATUS" ("ID_MOLD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AS_MOULES" ;
--------------------------------------------------------
--  Constraints for Table MOLD_STATUS
--------------------------------------------------------

  ALTER TABLE "AS_MOULES"."MOLD_STATUS" ADD CONSTRAINT "MOLD_STATUS_PK" PRIMARY KEY ("ID_MOLD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AS_MOULES"  ENABLE;
  ALTER TABLE "AS_MOULES"."MOLD_STATUS" MODIFY ("ID_MOLD" NOT NULL ENABLE);





--------------------------------------------------------
--  DDL for Table CODE_TECH
--------------------------------------------------------

  CREATE TABLE "AS_MOULES"."CODE_TECH" 
   (	"ID_CODE" VARCHAR2(5 BYTE), 
	"SALES_CODE" VARCHAR2(15 BYTE), 
	"BAGUES_TYPE" VARCHAR2(20 BYTE), 
	"SMARTEAM" DATE, 
	"TYPE_PRESSE" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AS_MOULES" ;
--------------------------------------------------------
--  DDL for Index CODE_TECH_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AS_MOULES"."CODE_TECH_PK" ON "AS_MOULES"."CODE_TECH" ("ID_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AS_MOULES" ;
--------------------------------------------------------
--  Constraints for Table CODE_TECH
--------------------------------------------------------

  ALTER TABLE "AS_MOULES"."CODE_TECH" ADD CONSTRAINT "CODE_TECH_PK" PRIMARY KEY ("ID_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AS_MOULES"  ENABLE;
  ALTER TABLE "AS_MOULES"."CODE_TECH" MODIFY ("ID_CODE" NOT NULL ENABLE);





--------------------------------------------------------
--  DDL for Table MOLD_TECH
--------------------------------------------------------

  CREATE TABLE "AS_MOULES"."MOLD_TECH" 
   (	"ID_MOLD" VARCHAR2(15 BYTE), 
	"NB_CYCLE_CUISSON_LIFE" NUMBER, 
	"NB_CYCLE_CUISSON_NOW" NUMBER, 
	"CLOGGED_HOLES" VARCHAR2(1 BYTE), 
	"DATE_GET_MOLD" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AS_MOULES" ;
REM INSERTING into AS_MOULES.MOLD_TECH
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index MOLD_TECH_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AS_MOULES"."MOLD_TECH_PK" ON "AS_MOULES"."MOLD_TECH" ("ID_MOLD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AS_MOULES" ;
--------------------------------------------------------
--  Constraints for Table MOLD_TECH
--------------------------------------------------------

  ALTER TABLE "AS_MOULES"."MOLD_TECH" ADD CONSTRAINT "MOLD_TECH_PK" PRIMARY KEY ("ID_MOLD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AS_MOULES"  ENABLE;
  ALTER TABLE "AS_MOULES"."MOLD_TECH" MODIFY ("ID_MOLD" NOT NULL ENABLE);





--------------------------------------------------------
--  DDL for Table MOLD_METROLOGY
--------------------------------------------------------

  CREATE TABLE "AS_MOULES"."MOLD_METROLOGY" 
   (	"ID_MOLD" VARCHAR2(15 BYTE), 
	"LAST_CHECK_DATE" DATE, 
	"LAST_RESULT" VARCHAR2(40 BYTE), 
	"COMMENT_METRO" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AS_MOULES" ;
REM INSERTING into AS_MOULES.MOLD_METROLOGY
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index MOLD_METROLOGY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AS_MOULES"."MOLD_METROLOGY_PK" ON "AS_MOULES"."MOLD_METROLOGY" ("ID_MOLD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AS_MOULES" ;
--------------------------------------------------------
--  Constraints for Table MOLD_METROLOGY
--------------------------------------------------------

  ALTER TABLE "AS_MOULES"."MOLD_METROLOGY" ADD CONSTRAINT "MOLD_METROLOGY_PK" PRIMARY KEY ("ID_MOLD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AS_MOULES"  ENABLE;
  ALTER TABLE "AS_MOULES"."MOLD_METROLOGY" MODIFY ("ID_MOLD" NOT NULL ENABLE);





--------------------------------------------------------
--  DDL for Table MOLD_EXEMPTION
--------------------------------------------------------

  CREATE TABLE "AS_MOULES"."MOLD_EXEMPTION" 
   (	"ID_MOLD" VARCHAR2(15 BYTE), 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"COMMENT_EXCEPT" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AS_MOULES" ;
REM INSERTING into AS_MOULES.MOLD_EXEMPTION
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index MOLD_EXEMPTION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AS_MOULES"."MOLD_EXEMPTION_PK" ON "AS_MOULES"."MOLD_EXEMPTION" ("ID_MOLD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AS_MOULES" ;
--------------------------------------------------------
--  Constraints for Table MOLD_EXEMPTION
--------------------------------------------------------

  ALTER TABLE "AS_MOULES"."MOLD_EXEMPTION" ADD CONSTRAINT "MOLD_EXEMPTION_PK" PRIMARY KEY ("ID_MOLD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AS_MOULES"  ENABLE;
  ALTER TABLE "AS_MOULES"."MOLD_EXEMPTION" MODIFY ("ID_MOLD" NOT NULL ENABLE);
