--------------------------------------------------------
--  Fichier cr�� - lundi-juillet-15-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table SUIVI_OP
--------------------------------------------------------

  CREATE TABLE "AS_MOULES"."SUIVI_OP" 
   (	"UTILISATEUR" VARCHAR2(50 BYTE), 
	"DATE_A" VARCHAR2(20 BYTE), 
	"HEURE_A" VARCHAR2(20 BYTE), 
	"DATE_D" VARCHAR2(20 BYTE), 
	"HEURE_D" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 2097152 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AS_MOULES" ;
--------------------------------------------------------
--  DDL for Table CAVITES
--------------------------------------------------------

  CREATE TABLE "AS_MOULES"."CAVITES" 
   (	"NO_PRESSE" VARCHAR2(6 BYTE), 
	"ID_CAVITE" VARCHAR2(1 BYTE) DEFAULT '-', 
	"FACT_CODE" VARCHAR2(4 BYTE) DEFAULT '-', 
	"LIBELLE" VARCHAR2(60 BYTE) DEFAULT '-', 
	"NO_MOULE" VARCHAR2(12 BYTE) DEFAULT '', 
	"NO_CONTAINER" VARCHAR2(12 BYTE) DEFAULT '', 
	"NB_CUISSONS" NUMBER DEFAULT 0, 
	"CMO_PREVU" NUMBER DEFAULT 0, 
	"NO_MOULE_MOLD_LIST" VARCHAR2(50 BYTE), 
	"CPT_NETTOYAGE_CRYO" NUMBER, 
	"CPT_MEMBRANE" NUMBER, 
	"CRYO_POSSIBLE" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AS_MOULES" ;
--------------------------------------------------------
--  DDL for Table EXT_MOLDEQUIPMENTSLIST
--------------------------------------------------------

  CREATE TABLE "AS_MOULES"."EXT_MOLDEQUIPMENTSLIST" 
   (	"REF_MOULE" VARCHAR2(20 BYTE), 
	"REF_CTN" VARCHAR2(50 BYTE), 
	"REF_SPECS" VARCHAR2(20 BYTE), 
	"REF_DIMENSION" VARCHAR2(100 BYTE), 
	"PATTERNSIZE" VARCHAR2(100 BYTE), 
	"CODE_PROD_2" VARCHAR2(100 BYTE), 
	"COMPTEUR_CUISSON_TOTAL" VARCHAR2(20 BYTE), 
	"STATUS_MOULE" VARCHAR2(40 BYTE), 
	"COMMENTAIRE_1" VARCHAR2(100 BYTE), 
	"TYPE_CTN2" VARCHAR2(20 BYTE), 
	"DIM_CTN2" VARCHAR2(20 BYTE), 
	"GOUPILLE2" VARCHAR2(20 BYTE), 
	"NB_GOUPILLE_COMPLET" VARCHAR2(20 BYTE), 
	"DATE_GOUPILLE_COMPLET" VARCHAR2(20 BYTE), 
	"DATE_LAST_CLEAN" VARCHAR2(20 BYTE), 
	"COMPTEUR_LAST_CLEAN" NUMBER(10,0), 
	"FLANCS_COMPATIBILITE" VARCHAR2(100 BYTE), 
	"DATE_PRESSE_DESC_CMO" VARCHAR2(20 BYTE), 
	"CODE_PROD_CONFIG" VARCHAR2(20 BYTE), 
	"INDICE_C_V" VARCHAR2(100 BYTE), 
	"POSITION_ACTUEL" VARCHAR2(20 BYTE), 
	"COMMENTAIRE_2" VARCHAR2(100 BYTE), 
	"HEURE_1ERE_PNEU" VARCHAR2(20 BYTE), 
	"GRADE_1ERE_PNEU" VARCHAR2(2 BYTE), 
	"HEURE_DERNIER_PNEU" VARCHAR2(20 BYTE), 
	"GRADE_DERNIER_PNEU" VARCHAR2(10 BYTE), 
	"COMPTEUR_MOULE_JANV2008" NUMBER(10,0), 
	"REF_MOULE_SIMPLE" VARCHAR2(10 BYTE), 
	"POSITION_ACTUEL_DATE" DATE, 
	"COMMENTAIRE" VARCHAR2(100 CHAR), 
	"REF_SEGMENT" VARCHAR2(20 CHAR), 
	"REF_FLANC_SUP" VARCHAR2(20 CHAR), 
	"REF_FLANC_INF" VARCHAR2(20 CHAR), 
	"GSWR_TOP" VARCHAR2(20 BYTE), 
	"GSWR_BOTTOM" VARCHAR2(20 BYTE), 
	"GTRD" VARCHAR2(20 BYTE), 
	"DRAWING" VARCHAR2(20 BYTE), 
	"REVISION" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 327680 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AS_MOULES" ;
--------------------------------------------------------
--  DDL for Table CAVITESCOP
--------------------------------------------------------

  CREATE TABLE "AS_MOULES"."CAVITESCOP" 
   (	"NO_PRESSE" VARCHAR2(4 BYTE), 
	"ID_CAVITE" VARCHAR2(1 BYTE), 
	"FACT_CODE" VARCHAR2(4 BYTE), 
	"LIBELLE" VARCHAR2(60 BYTE), 
	"NO_MOULE" VARCHAR2(12 BYTE), 
	"NO_CONTAINER" VARCHAR2(12 BYTE), 
	"NB_CUISSONS" NUMBER, 
	"CMO_PREVU" NUMBER, 
	"NO_MOULE_MOLD_LIST" VARCHAR2(50 BYTE), 
	"CPT_NETTOYAGE_CRYO" NUMBER, 
	"CPT_MEMBRANE" NUMBER, 
	"CRYO_POSSIBLE" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AS_MOULES" ;
--------------------------------------------------------
--  DDL for Table PRESSESCOP
--------------------------------------------------------

  CREATE TABLE "AS_MOULES"."PRESSESCOP" 
   (	"NO_PRESSE" VARCHAR2(4 BYTE), 
	"NB_CAVITES" NUMBER, 
	"TYPE_PRESSE" VARCHAR2(16 BYTE), 
	"TYPE_STD" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AS_MOULES" ;
--------------------------------------------------------
--  DDL for Table LISTE_OP
--------------------------------------------------------

  CREATE TABLE "AS_MOULES"."LISTE_OP" 
   (	"NOM" VARCHAR2(50 BYTE), 
	"EQUIPE" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AS_MOULES" ;
--------------------------------------------------------
--  DDL for Table TREADSET
--------------------------------------------------------

  CREATE TABLE "AS_MOULES"."TREADSET" 
   (	"FACT_CODE" VARCHAR2(5 BYTE), 
	"N1" VARCHAR2(2 BYTE), 
	"N2" VARCHAR2(2 BYTE), 
	"N3" VARCHAR2(2 BYTE), 
	"N4" VARCHAR2(2 BYTE), 
	"S1" VARCHAR2(2 BYTE), 
	"S2" VARCHAR2(2 BYTE), 
	"S3" VARCHAR2(2 BYTE), 
	"S4" VARCHAR2(2 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AS_MOULES" ;
--------------------------------------------------------
--  DDL for Table IMPRESSION_CRYO
--------------------------------------------------------

  CREATE TABLE "AS_MOULES"."IMPRESSION_CRYO" 
   (	"DATE_CRYO" VARCHAR2(20 BYTE), 
	"TYPE_CRYO" VARCHAR2(20 BYTE), 
	"COMMENTAIRE_CRYO" VARCHAR2(100 BYTE), 
	"NUM_PRESSE" VARCHAR2(10 BYTE), 
	"NUM_MOULE_MOLD_LIST" VARCHAR2(20 BYTE), 
	"FACT_CODE" VARCHAR2(50 BYTE), 
	"LIBELLE" VARCHAR2(100 BYTE), 
	"CPT_CUISSON_PRESSE" NUMBER, 
	"CPT_CUISSON_MOULE" NUMBER, 
	"DATE_DERNIERE_CRYO" VARCHAR2(20 BYTE), 
	"CPT_CUISSON_DERNIERE_CRYO" NUMBER, 
	"VALIDATION" VARCHAR2(20 BYTE), 
	"DESIGNATION_CRYO" VARCHAR2(150 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AS_MOULES" ;
--------------------------------------------------------
--  DDL for Table BDUSERS
--------------------------------------------------------

  CREATE TABLE "AS_MOULES"."BDUSERS" 
   (	"PLANT" VARCHAR2(1 BYTE), 
	"USER_NAME" VARCHAR2(16 BYTE), 
	"USER_LONG_NAME" VARCHAR2(32 BYTE) DEFAULT '-', 
	"USER_RIGHTS" CLOB DEFAULT '-'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AS_MOULES" 
 LOB ("USER_RIGHTS") STORE AS BASICFILE "SYS_LOB0000102267C00004$$"(
  TABLESPACE "AS_MOULES" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table SUIVI_GRADE
--------------------------------------------------------

  CREATE TABLE "AS_MOULES"."SUIVI_GRADE" 
   (	"NUM_PRESSE" VARCHAR2(4 BYTE), 
	"DATE_1ERE_ENV" DATE, 
	"GRADE_1ERE_ENV" NUMBER, 
	"DATE_CTRL_INTERM" DATE, 
	"GRADE_CTRL_INTERM" NUMBER, 
	"DATE_DERN_ENV" DATE, 
	"GRADE_DERN_ENV" NUMBER, 
	"FACT_CODE" VARCHAR2(50 BYTE), 
	"LIBELLE" VARCHAR2(100 BYTE), 
	"NO_MOULE" VARCHAR2(50 BYTE), 
	"NO_MOULE_MOLD_LIST" VARCHAR2(50 BYTE), 
	"NB_CUISSONS_PRESSE" NUMBER, 
	"CPT_CUISSON_TOTAL" NUMBER, 
	"COMMENTAIRES" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 2097152 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AS_MOULES" ;
--------------------------------------------------------
--  DDL for Table PASSWORD
--------------------------------------------------------

  CREATE TABLE "AS_MOULES"."PASSWORD" 
   (	"NOM_EQUIPE" VARCHAR2(20 BYTE), 
	"PASS" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AS_MOULES" ;
--------------------------------------------------------
--  DDL for Table SUIVI_CRYO
--------------------------------------------------------

  CREATE TABLE "AS_MOULES"."SUIVI_CRYO" 
   (	"DATE_CRYO" VARCHAR2(20 BYTE), 
	"TYPE_CRYO" VARCHAR2(20 BYTE), 
	"COMMENTAIRE_CRYO" VARCHAR2(100 BYTE), 
	"NUM_PRESSE" VARCHAR2(10 BYTE), 
	"NUM_MOULE_MOLD_LIST" VARCHAR2(20 BYTE), 
	"FACT_CODE" VARCHAR2(50 BYTE), 
	"LIBELLE" VARCHAR2(100 BYTE), 
	"CPT_CUISSON_PRESSE" NUMBER, 
	"CPT_CUISSON_MOULE" NUMBER, 
	"DATE_DERNIERE_CRYO" VARCHAR2(20 BYTE), 
	"CPT_CUISSON_DERNIERE_CRYO" NUMBER, 
	"VALIDATION" VARCHAR2(20 BYTE), 
	"DESIGNATION_CRYO" VARCHAR2(150 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 5242880 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AS_MOULES" ;
--------------------------------------------------------
--  DDL for Table RAPPORT_ACTIVITE_MOULE
--------------------------------------------------------

  CREATE TABLE "AS_MOULES"."RAPPORT_ACTIVITE_MOULE" 
   (	"EQUIPE1" VARCHAR2(5 BYTE), 
	"EQUIPE2" VARCHAR2(5 BYTE), 
	"NOM1" VARCHAR2(100 BYTE), 
	"NOM2" VARCHAR2(100 BYTE), 
	"TYPE_INTERVENTION" VARCHAR2(100 BYTE), 
	"PRESSE" VARCHAR2(10 BYTE), 
	"NO_MOULE" VARCHAR2(20 BYTE), 
	"HEURE_DEBUT" VARCHAR2(40 BYTE), 
	"HEURE_FIN" VARCHAR2(40 BYTE), 
	"NB_CALORIFUGE_BIN" NUMBER, 
	"ALTERNANCE_PROC�DURE" VARCHAR2(100 BYTE), 
	"COMMENTAIRE" VARCHAR2(200 BYTE), 
	"SABL_ACTION1" VARCHAR2(10 BYTE), 
	"SABL_ACTION2" VARCHAR2(10 BYTE), 
	"SABL_ACTION3" VARCHAR2(10 BYTE), 
	"SABL_ACTION4" VARCHAR2(10 BYTE), 
	"SABL_POUR_CTRL_MOULE" VARCHAR2(10 BYTE), 
	"SABL_POUR_ATELIER" VARCHAR2(10 BYTE), 
	"SABL_POUR_CRYO" VARCHAR2(10 BYTE), 
	"SABL_CMPT_CRYO" NUMBER, 
	"SABL_CHECK1" NUMBER, 
	"SABL_CHECK2" VARCHAR2(10 BYTE), 
	"SABL_CHECK3" VARCHAR2(10 BYTE), 
	"SABL_CHECK4" VARCHAR2(10 BYTE), 
	"RELEVE_CMO" VARCHAR2(200 BYTE), 
	"RELEVE_SABL" VARCHAR2(200 BYTE), 
	"RELEVE_CHAUFFAGE" VARCHAR2(200 BYTE), 
	"RELEVE_COMMENTAIRE" VARCHAR2(200 BYTE), 
	"ERREUR_TYPE" VARCHAR2(20 BYTE), 
	"ERREUR_QUOTATION" NUMBER, 
	"ERREUR_COMMENTAIRE" VARCHAR2(200 BYTE), 
	"INDEX_TAB" NUMBER, 
	"TRAVAIL_COTATION" NUMBER, 
	"CALENDRIER" VARCHAR2(40 BYTE), 
	"SABL_ACTION_NET" VARCHAR2(10 BYTE), 
	"SABL_NET_CMO" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 12582912 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AS_MOULES" ;
--------------------------------------------------------
--  DDL for Table EXT_MOLDEQUIPMENTSPEC
--------------------------------------------------------

  CREATE TABLE "AS_MOULES"."EXT_MOLDEQUIPMENTSPEC" 
   (	"REF_SPEC" VARCHAR2(20 BYTE), 
	"CODE_PROD_1" VARCHAR2(20 BYTE), 
	"HEURE_RECORD_DATA" VARCHAR2(20 BYTE), 
	"N_SPEC_EQUIP" VARCHAR2(20 BYTE), 
	"CODE_PROFIL" VARCHAR2(20 BYTE), 
	"INDICE_C_V" VARCHAR2(20 BYTE), 
	"PATTERNSIZE" VARCHAR2(100 BYTE), 
	"TREAD_RAYON" VARCHAR2(20 BYTE), 
	"TREAD_STELL" VARCHAR2(20 BYTE), 
	"TREAD_NYLON" VARCHAR2(20 BYTE), 
	"TREAD_PLIES" VARCHAR2(20 BYTE), 
	"INMETRO" VARCHAR2(20 BYTE), 
	"CODE_DOT" VARCHAR2(20 BYTE), 
	"CODE_HOMOLOGATION" VARCHAR2(20 BYTE), 
	"CODE_ENOISE" VARCHAR2(20 BYTE), 
	"MLD_KG" VARCHAR2(20 BYTE), 
	"MLD_LBS" VARCHAR2(20 BYTE), 
	"MLS_KG" VARCHAR2(20 BYTE), 
	"MLS_LBS" VARCHAR2(20 BYTE), 
	"MPRESSE_KPA" VARCHAR2(20 BYTE), 
	"MPRESSE_PSI" VARCHAR2(20 BYTE), 
	"TYPE_CTN" VARCHAR2(20 BYTE), 
	"DIM_CTN" VARCHAR2(20 BYTE), 
	"GOUPILLE" VARCHAR2(20 BYTE), 
	"BAGO_BMR" VARCHAR2(30 BYTE), 
	"BAGO_TMR" VARCHAR2(30 BYTE), 
	"BAGO_ADAPTER" VARCHAR2(30 BYTE), 
	"BAGO_BLADDER" VARCHAR2(30 BYTE), 
	"MHI_BMR" VARCHAR2(30 BYTE), 
	"MHI_BLADDER" VARCHAR2(30 BYTE), 
	"JEUX_TOTAL_SECTEUR" NUMBER, 
	"S_DIAMETRE" NUMBER, 
	"L_DIAMETRE" NUMBER, 
	"CODE_A_DOT" VARCHAR2(20 BYTE), 
	"CODE_A_HOMOLOGATION" VARCHAR2(20 BYTE), 
	"CODE_A_ENOISE" VARCHAR2(20 BYTE), 
	"A_INMETRO" VARCHAR2(20 BYTE), 
	"EXTRALOAD" VARCHAR2(20 BYTE), 
	"CODE_PROD_POSSIBLE" VARCHAR2(100 BYTE), 
	"NB_MOULES_MAXI_CODE" NUMBER, 
	"NB_MOULES_SPARE" NUMBER, 
	"SEUIL_CRYO_CODE" NUMBER, 
	"M_PLUS_S_BOT" VARCHAR2(5 BYTE), 
	"SNOWFLAKE_BOT" VARCHAR2(5 BYTE), 
	"M_PLUS_S_TOP" VARCHAR2(5 BYTE), 
	"SNOWFLAKE_TOP" VARCHAR2(5 BYTE), 
	"MDF_BOT" VARCHAR2(5 BYTE), 
	"MDF_TOP" VARCHAR2(5 BYTE), 
	"EXTRALOAD_BOT" VARCHAR2(5 BYTE), 
	"EXTRALOAD_TOP" VARCHAR2(5 BYTE), 
	"C_PROFIL_BOT" VARCHAR2(5 BYTE), 
	"C_PROFIL_TOP" VARCHAR2(5 BYTE), 
	"C_TREAD_BOT" VARCHAR2(5 BYTE), 
	"C_SW_BOT" VARCHAR2(5 BYTE), 
	"C_TREAD_TOP" VARCHAR2(5 BYTE), 
	"C_SW_TOP" VARCHAR2(5 BYTE), 
	"RADIAL_BOT" VARCHAR2(5 BYTE), 
	"TUBELESS_BOT" VARCHAR2(5 BYTE), 
	"RADIAL_TOP" VARCHAR2(5 BYTE), 
	"TUBELESS_TOP" VARCHAR2(5 BYTE), 
	"MAX_LOAD_BOT" VARCHAR2(5 BYTE), 
	"MAX_PRESS_BOT" VARCHAR2(5 BYTE), 
	"MAX_LOAD_TOP" VARCHAR2(5 BYTE), 
	"MAX_PRESS_TOP" VARCHAR2(5 BYTE), 
	"TREADWEAR_BOT" VARCHAR2(10 BYTE), 
	"TREADWEAR_TOP" VARCHAR2(10 BYTE), 
	"S_WARNING_BOT" VARCHAR2(5 BYTE), 
	"S_WARNING_TOP" VARCHAR2(5 BYTE), 
	"OUTSIDE_BOT" VARCHAR2(5 BYTE), 
	"INSIDE_TOP" VARCHAR2(5 BYTE), 
	"S_ROTATION_BOT" VARCHAR2(5 BYTE), 
	"S_ROTATION_TOP" VARCHAR2(5 BYTE), 
	"NB_TWI_BOT" VARCHAR2(5 BYTE), 
	"NB_TWI_TOP" VARCHAR2(5 BYTE), 
	"BAGUE_INF_VISIBLE" VARCHAR2(5 BYTE), 
	"BAGUE_SUP_VISIBLE" VARCHAR2(5 BYTE), 
	"PATTERNSIZE_TOP" VARCHAR2(100 BYTE), 
	"INDICE_C_V_TOP" VARCHAR2(5 BYTE), 
	"COM_SPECIF" VARCHAR2(200 BYTE), 
	"CODE_PROD_LIE" VARCHAR2(150 BYTE), 
	"S_DIA_RELIEVE" VARCHAR2(5 BYTE), 
	"STATUS" VARCHAR2(20 BYTE), 
	"T_MINI" VARCHAR2(15 CHAR), 
	"T_MAXI" VARCHAR2(15 CHAR), 
	"COM_DIVERS" VARCHAR2(200 BYTE), 
	"DIMENSION" VARCHAR2(100 BYTE), 
	"USA_CODE" VARCHAR2(10 CHAR), 
	"CCCS" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AS_MOULES" ;
--------------------------------------------------------
--  DDL for Table LOG_CMOS
--------------------------------------------------------

  CREATE TABLE "AS_MOULES"."LOG_CMOS" 
   (	"FACT_CODE" VARCHAR2(4 BYTE), 
	"DATE_UPD" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AS_MOULES" ;
--------------------------------------------------------
--  DDL for Table SUIVI_CRYO_OLD
--------------------------------------------------------

  CREATE TABLE "AS_MOULES"."SUIVI_CRYO_OLD" 
   (	"DATE_CRYO" VARCHAR2(20 BYTE), 
	"TYPE_CRYO" VARCHAR2(20 BYTE), 
	"COMMENTAIRE_CRYO" VARCHAR2(100 BYTE), 
	"NUM_PRESSE" VARCHAR2(10 BYTE), 
	"NUM_MOULE_MOLD_LIST" VARCHAR2(20 BYTE), 
	"FACT_CODE" VARCHAR2(50 BYTE), 
	"LIBELLE" VARCHAR2(100 BYTE), 
	"CPT_CUISSON_PRESSE" NUMBER, 
	"CPT_CUISSON_MOULE" NUMBER, 
	"DATE_DERNIERE_CRYO" VARCHAR2(20 BYTE), 
	"CPT_CUISSON_DERNIERE_CRYO" NUMBER, 
	"VALIDATION" VARCHAR2(20 BYTE), 
	"DESIGNATION_CRYO" VARCHAR2(150 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 2097152 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CMOS
--------------------------------------------------------

  CREATE TABLE "AS_MOULES"."CMOS" 
   (	"NO_CMO" NUMBER, 
	"DATE_CMO" DATE, 
	"NO_PRESSE" VARCHAR2(4 BYTE), 
	"ID_CAVITE" VARCHAR2(1 BYTE) DEFAULT '-', 
	"D_FACT_CODE" VARCHAR2(4 BYTE) DEFAULT '-', 
	"D_LIBELLE" VARCHAR2(65 BYTE) DEFAULT '-', 
	"D_NO_MOULE" VARCHAR2(12 BYTE) DEFAULT '-', 
	"D_NO_CONTAINER" VARCHAR2(12 BYTE) DEFAULT '-', 
	"M_FACT_CODE" VARCHAR2(4 BYTE) DEFAULT '-', 
	"M_LIBELLE" VARCHAR2(65 BYTE) DEFAULT '-', 
	"M_NO_MOULE" VARCHAR2(12 BYTE) DEFAULT '', 
	"M_NO_CONTAINER" VARCHAR2(12 BYTE) DEFAULT '', 
	"STATUS" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"REMARKS" CLOB DEFAULT '-', 
	"TYPE_CMO" VARCHAR2(16 BYTE) DEFAULT '-', 
	"D_CPTCUISSON" NUMBER, 
	"D_NO_MOULE_MOLD_LIST" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AS_MOULES" 
 LOB ("REMARKS") STORE AS BASICFILE "SYS_LOB0000102270C00014$$"(
  TABLESPACE "AS_MOULES" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table NUMCMO
--------------------------------------------------------

  CREATE TABLE "AS_MOULES"."NUMCMO" 
   (	"NO_CMO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AS_MOULES" ;
--------------------------------------------------------
--  DDL for Table SUIVI
--------------------------------------------------------

  CREATE TABLE "AS_MOULES"."SUIVI" 
   (	"UTILISATEUR" VARCHAR2(50 BYTE), 
	"NUM_MOULE" VARCHAR2(50 BYTE), 
	"CODE_PROD" VARCHAR2(50 BYTE), 
	"LIBELLE_DIMENSION" VARCHAR2(50 BYTE), 
	"EMPLACEMENT_AVANT" VARCHAR2(50 BYTE), 
	"EMPLACEMENT_APRES" VARCHAR2(50 BYTE), 
	"DATE_DEPLACEMENT" VARCHAR2(20 BYTE), 
	"HEURE_DEPLACEMENT" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 5242880 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AS_MOULES" ;
--------------------------------------------------------
--  DDL for Table PRESSES
--------------------------------------------------------

  CREATE TABLE "AS_MOULES"."PRESSES" 
   (	"NO_PRESSE" VARCHAR2(4 BYTE), 
	"NB_CAVITES" NUMBER, 
	"TYPE_PRESSE" VARCHAR2(16 BYTE), 
	"TYPE_STD" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AS_MOULES" ;
--------------------------------------------------------
--  DDL for Table ARCHIVAGE_SPECS
--------------------------------------------------------

  CREATE TABLE "AS_MOULES"."ARCHIVAGE_SPECS" 
   (	"REF_SPEC" VARCHAR2(20 BYTE), 
	"CODE_PROD_1" VARCHAR2(20 BYTE), 
	"HEURE_RECORD_DATA" VARCHAR2(20 BYTE), 
	"N_SPEC_EQUIP" VARCHAR2(20 BYTE), 
	"CODE_PROFIL" VARCHAR2(20 BYTE), 
	"INDICE_C_V" VARCHAR2(20 BYTE), 
	"PATTERNSIZE" VARCHAR2(100 BYTE), 
	"TREAD_RAYON" VARCHAR2(20 BYTE), 
	"TREAD_STELL" VARCHAR2(20 BYTE), 
	"TREAD_NYLON" VARCHAR2(20 BYTE), 
	"TREAD_PLIES" VARCHAR2(20 BYTE), 
	"INMETRO" VARCHAR2(20 BYTE), 
	"CODE_DOT" VARCHAR2(20 BYTE), 
	"CODE_HOMOLOGATION" VARCHAR2(20 BYTE), 
	"CODE_ENOISE" VARCHAR2(20 BYTE), 
	"MLD_KG" VARCHAR2(20 BYTE), 
	"MLD_LBS" VARCHAR2(20 BYTE), 
	"MLS_KG" VARCHAR2(20 BYTE), 
	"MLS_LBS" VARCHAR2(20 BYTE), 
	"MPRESSE_KPA" VARCHAR2(20 BYTE), 
	"MPRESSE_PSI" VARCHAR2(20 BYTE), 
	"TYPE_CTN" VARCHAR2(20 BYTE), 
	"DIM_CTN" VARCHAR2(20 BYTE), 
	"GOUPILLE" VARCHAR2(20 BYTE), 
	"BAGO_BMR" VARCHAR2(30 BYTE), 
	"BAGO_TMR" VARCHAR2(30 BYTE), 
	"BAGO_ADAPTER" VARCHAR2(30 BYTE), 
	"BAGO_BLADDER" VARCHAR2(30 BYTE), 
	"MHI_BMR" VARCHAR2(30 BYTE), 
	"MHI_BLADDER" VARCHAR2(30 BYTE), 
	"JEUX_TOTAL_SECTEUR" NUMBER, 
	"S_DIAMETRE" NUMBER, 
	"L_DIAMETRE" NUMBER, 
	"CODE_A_DOT" VARCHAR2(20 BYTE), 
	"CODE_A_HOMOLOGATION" VARCHAR2(20 BYTE), 
	"CODE_A_ENOISE" VARCHAR2(20 BYTE), 
	"A_INMETRO" VARCHAR2(20 BYTE), 
	"EXTRALOAD" VARCHAR2(20 BYTE), 
	"CODE_PROD_POSSIBLE" VARCHAR2(100 BYTE), 
	"NB_MOULES_MAXI_CODE" NUMBER, 
	"NB_MOULES_SPARE" NUMBER, 
	"SEUIL_CRYO_CODE" NUMBER, 
	"M_PLUS_S_BOT" VARCHAR2(5 BYTE), 
	"SNOWFLAKE_BOT" VARCHAR2(5 BYTE), 
	"M_PLUS_S_TOP" VARCHAR2(5 BYTE), 
	"SNOWFLAKE_TOP" VARCHAR2(5 BYTE), 
	"MDF_BOT" VARCHAR2(5 BYTE), 
	"MDF_TOP" VARCHAR2(5 BYTE), 
	"EXTRALOAD_BOT" VARCHAR2(5 BYTE), 
	"EXTRALOAD_TOP" VARCHAR2(5 BYTE), 
	"C_PROFIL_BOT" VARCHAR2(5 BYTE), 
	"C_PROFIL_TOP" VARCHAR2(5 BYTE), 
	"C_TREAD_BOT" VARCHAR2(5 BYTE), 
	"C_SW_BOT" VARCHAR2(5 BYTE), 
	"C_TREAD_TOP" VARCHAR2(5 BYTE), 
	"C_SW_TOP" VARCHAR2(5 BYTE), 
	"RADIAL_BOT" VARCHAR2(5 BYTE), 
	"TUBELESS_BOT" VARCHAR2(5 BYTE), 
	"RADIAL_TOP" VARCHAR2(5 BYTE), 
	"TUBELESS_TOP" VARCHAR2(5 BYTE), 
	"MAX_LOAD_BOT" VARCHAR2(5 BYTE), 
	"MAX_PRESS_BOT" VARCHAR2(5 BYTE), 
	"MAX_LOAD_TOP" VARCHAR2(5 BYTE), 
	"MAX_PRESS_TOP" VARCHAR2(5 BYTE), 
	"TREADWEAR_BOT" VARCHAR2(10 BYTE), 
	"TREADWEAR_TOP" VARCHAR2(10 BYTE), 
	"S_WARNING_BOT" VARCHAR2(5 BYTE), 
	"S_WARNING_TOP" VARCHAR2(5 BYTE), 
	"OUTSIDE_BOT" VARCHAR2(5 BYTE), 
	"INSIDE_TOP" VARCHAR2(5 BYTE), 
	"S_ROTATION_BOT" VARCHAR2(5 BYTE), 
	"S_ROTATION_TOP" VARCHAR2(5 BYTE), 
	"NB_TWI_BOT" VARCHAR2(5 BYTE), 
	"NB_TWI_TOP" VARCHAR2(5 BYTE), 
	"BAGUE_INF_VISIBLE" VARCHAR2(5 BYTE), 
	"BAGUE_SUP_VISIBLE" VARCHAR2(5 BYTE), 
	"PATTERNSIZE_TOP" VARCHAR2(100 BYTE), 
	"INDICE_C_V_TOP" VARCHAR2(5 BYTE), 
	"COM_SPECIF" VARCHAR2(200 BYTE), 
	"CODE_PROD_LIE" VARCHAR2(150 BYTE), 
	"S_DIA_RELIEVE" VARCHAR2(5 BYTE), 
	"STATUS" VARCHAR2(20 BYTE), 
	"T_MINI" NUMBER, 
	"T_MAXI" NUMBER, 
	"COM_DIVERS" VARCHAR2(200 BYTE), 
	"DIMENSION" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AS_MOULES" ;
--------------------------------------------------------
--  DDL for Table SPECS
--------------------------------------------------------

  CREATE TABLE "AS_MOULES"."SPECS" 
   (	"TS_CODE" VARCHAR2(8 BYTE), 
	"FACT_CODE" VARCHAR2(5 BYTE), 
	"DOT_SERIAL" VARCHAR2(20 BYTE), 
	"SP_TYPE" VARCHAR2(10 BYTE), 
	"BRANDNAME" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AS_MOULES" ;
--------------------------------------------------------
--  DDL for Table ARCHIVAGE_MOULES
--------------------------------------------------------

  CREATE TABLE "AS_MOULES"."ARCHIVAGE_MOULES" 
   (	"REF_MOULE" VARCHAR2(20 BYTE), 
	"REF_CTN" VARCHAR2(50 BYTE), 
	"REF_SPECS" VARCHAR2(20 BYTE), 
	"REF_DIMENSION" VARCHAR2(100 BYTE), 
	"PATTERNSIZE" VARCHAR2(100 BYTE), 
	"CODE_PROD_2" VARCHAR2(100 BYTE), 
	"COMPTEUR_CUISSON_TOTAL" VARCHAR2(20 BYTE), 
	"STATUS_MOULE" VARCHAR2(20 BYTE), 
	"COMMENTAIRE_1" VARCHAR2(100 BYTE), 
	"TYPE_CTN2" VARCHAR2(20 BYTE), 
	"DIM_CTN2" VARCHAR2(20 BYTE), 
	"GOUPILLE2" VARCHAR2(20 BYTE), 
	"NB_GOUPILLE_COMPLET" VARCHAR2(20 BYTE), 
	"DATE_GOUPILLE_COMPLET" VARCHAR2(20 BYTE), 
	"DATE_LAST_CLEAN" VARCHAR2(20 BYTE), 
	"COMPTEUR_LAST_CLEAN" NUMBER(10,0), 
	"FLANCS_COMPATIBILITE" VARCHAR2(100 BYTE), 
	"DATE_PRESSE_DESC_CMO" VARCHAR2(20 BYTE), 
	"CODE_PROD_CONFIG" VARCHAR2(20 BYTE), 
	"INDICE_C_V" VARCHAR2(20 BYTE), 
	"POSITION_ACTUEL" VARCHAR2(20 BYTE), 
	"COMMENTAIRE_2" VARCHAR2(100 BYTE), 
	"HEURE_1ERE_PNEU" VARCHAR2(20 BYTE), 
	"GRADE_1ERE_PNEU" VARCHAR2(2 BYTE), 
	"HEURE_DERNIER_PNEU" VARCHAR2(20 BYTE), 
	"GRADE_DERNIER_PNEU" VARCHAR2(10 BYTE), 
	"COMPTEUR_MOULE_JANV2008" NUMBER(10,0), 
	"REF_MOULE_SIMPLE" VARCHAR2(10 BYTE), 
	"POSITION_ACTUEL_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AS_MOULES" ;
--------------------------------------------------------
--  DDL for Table CURES
--------------------------------------------------------

  CREATE TABLE "AS_MOULES"."CURES" 
   (	"TS_CODE" VARCHAR2(8 BYTE), 
	"FACT_CODE" VARCHAR2(4 BYTE), 
	"CU_CODE" VARCHAR2(20 BYTE), 
	"BLAD_CODE" VARCHAR2(16 BYTE), 
	"MINUTES" VARCHAR2(5 BYTE), 
	"CU_TYPE" VARCHAR2(4 BYTE), 
	"BAG_INF" VARCHAR2(25 BYTE), 
	"BAG_INT_SUP" VARCHAR2(25 BYTE), 
	"FR_SUP" VARCHAR2(25 BYTE), 
	"BASE_INT" VARCHAR2(25 BYTE), 
	"BASE_SUP" VARCHAR2(25 BYTE), 
	"HAELME" VARCHAR2(5 BYTE), 
	"LOTOEN" VARCHAR2(5 BYTE), 
	"MAT_MOU" VARCHAR2(6 BYTE), 
	"TYP_MOU" VARCHAR2(10 BYTE), 
	"HO_CODE" VARCHAR2(12 BYTE), 
	"KG_DUAL" NUMBER DEFAULT 0, 
	"KG_SINGLE" NUMBER DEFAULT 0, 
	"LBS_DUAL" NUMBER DEFAULT 0, 
	"LBS_SINGLE" NUMBER DEFAULT 0, 
	"TREAD" VARCHAR2(10 BYTE) DEFAULT '-', 
	"SIDEWALL" VARCHAR2(10 BYTE) DEFAULT '-', 
	"KPA" NUMBER DEFAULT 0, 
	"PSI" NUMBER DEFAULT 0, 
	"NOISE_CODE" VARCHAR2(16 BYTE) DEFAULT '-', 
	"INFLATE_P1" NUMBER DEFAULT 0, 
	"INFLATE_P2" NUMBER DEFAULT 0, 
	"INFLATE_P3" NUMBER DEFAULT 0, 
	"TEMP_PLAT" NUMBER DEFAULT 0, 
	"FORCE_CLOSE" NUMBER DEFAULT 0, 
	"VAPEUR" NUMBER DEFAULT 0, 
	"AZOTE" NUMBER DEFAULT 0, 
	"BLOC_AZOTE" NUMBER DEFAULT 0, 
	"RECUP_AZOTE" NUMBER DEFAULT 0, 
	"DRAIN" NUMBER DEFAULT 0, 
	"VIDE" NUMBER DEFAULT 0, 
	"SCREWS" VARCHAR2(10 BYTE) DEFAULT '-', 
	"REP_INV" VARCHAR2(1 BYTE) DEFAULT 'F', 
	"FC_MINI" NUMBER DEFAULT 0, 
	"INMETRO" VARCHAR2(20 BYTE) DEFAULT '-', 
	"REMARKS" CLOB, 
	"GRAV_DOT" VARCHAR2(30 BYTE), 
	"GRAV_INMETRO" VARCHAR2(30 BYTE), 
	"GRAV_HOCODE" VARCHAR2(30 BYTE), 
	"GRAV_NOISECODE" VARCHAR2(30 BYTE), 
	"DECROCH_FLANC" VARCHAR2(30 BYTE), 
	"PCI" VARCHAR2(30 BYTE), 
	"PRS_GONFLAGE" NUMBER, 
	"DIST_JANTE" NUMBER, 
	"MIN_PCI" VARCHAR2(30 BYTE), 
	"DIST_JANTE_MAX" NUMBER, 
	"QTE_CHARIOT" VARCHAR2(30 BYTE), 
	"USA_CANADA_CODE" VARCHAR2(30 BYTE), 
	"CCCS_CHINA" VARCHAR2(30 BYTE), 
	"GRAV_CCCS_CHINA" VARCHAR2(30 BYTE), 
	"HAUT_CHARG" NUMBER DEFAULT 0, 
	"VAL_OUTIL" VARCHAR2(5 BYTE) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AS_MOULES" 
 LOB ("REMARKS") STORE AS BASICFILE "SYS_LOB0000102279C00041$$"(
  TABLESPACE "AS_MOULES" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table SUIVI_GOUPILLE
--------------------------------------------------------

  CREATE TABLE "AS_MOULES"."SUIVI_GOUPILLE" 
   (	"TYPE_INTERVENTION" VARCHAR2(20 BYTE), 
	"NUM_PRESSE" VARCHAR2(10 BYTE), 
	"DATE_REGOUP" DATE, 
	"NB_GOUP_CHANGE" VARCHAR2(150 BYTE), 
	"NUM_MOULE" VARCHAR2(20 BYTE), 
	"FACT_CODE" VARCHAR2(50 BYTE), 
	"LIBELLE" VARCHAR2(100 BYTE), 
	"NUM_BIBLE_MOLD_LIST" VARCHAR2(20 BYTE), 
	"NB_CUISSON_PRESSE" NUMBER, 
	"NB_CUISSON_MOULE" NUMBER, 
	"TYPE_GOUPILLE" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 393216 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AS_MOULES" ;
REM INSERTING into AS_MOULES.SUIVI_OP
SET DEFINE OFF;
REM INSERTING into AS_MOULES.CAVITES
SET DEFINE OFF;
REM INSERTING into AS_MOULES.EXT_MOLDEQUIPMENTSLIST
SET DEFINE OFF;
REM INSERTING into AS_MOULES.CAVITESCOP
SET DEFINE OFF;
REM INSERTING into AS_MOULES.PRESSESCOP
SET DEFINE OFF;
REM INSERTING into AS_MOULES.LISTE_OP
SET DEFINE OFF;
REM INSERTING into AS_MOULES.TREADSET
SET DEFINE OFF;
REM INSERTING into AS_MOULES.IMPRESSION_CRYO
SET DEFINE OFF;
REM INSERTING into AS_MOULES.BDUSERS
SET DEFINE OFF;
REM INSERTING into AS_MOULES.SUIVI_GRADE
SET DEFINE OFF;
REM INSERTING into AS_MOULES.PASSWORD
SET DEFINE OFF;
REM INSERTING into AS_MOULES.SUIVI_CRYO
SET DEFINE OFF;
REM INSERTING into AS_MOULES.RAPPORT_ACTIVITE_MOULE
SET DEFINE OFF;
REM INSERTING into AS_MOULES.EXT_MOLDEQUIPMENTSPEC
SET DEFINE OFF;
REM INSERTING into AS_MOULES.LOG_CMOS
SET DEFINE OFF;
REM INSERTING into AS_MOULES.SUIVI_CRYO_OLD
SET DEFINE OFF;
REM INSERTING into AS_MOULES.CMOS
SET DEFINE OFF;
REM INSERTING into AS_MOULES.NUMCMO
SET DEFINE OFF;
REM INSERTING into AS_MOULES.SUIVI
SET DEFINE OFF;
REM INSERTING into AS_MOULES.PRESSES
SET DEFINE OFF;
REM INSERTING into AS_MOULES.ARCHIVAGE_SPECS
SET DEFINE OFF;
REM INSERTING into AS_MOULES.SPECS
SET DEFINE OFF;
REM INSERTING into AS_MOULES.ARCHIVAGE_MOULES
SET DEFINE OFF;
REM INSERTING into AS_MOULES.CURES
SET DEFINE OFF;
REM INSERTING into AS_MOULES.SUIVI_GOUPILLE
SET DEFINE OFF;
--------------------------------------------------------
--  Constraints for Table CAVITES
--------------------------------------------------------

  ALTER TABLE "AS_MOULES"."CAVITES" MODIFY ("NO_PRESSE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EXT_MOLDEQUIPMENTSLIST
--------------------------------------------------------

  ALTER TABLE "AS_MOULES"."EXT_MOLDEQUIPMENTSLIST" MODIFY ("REF_MOULE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CAVITESCOP
--------------------------------------------------------

  ALTER TABLE "AS_MOULES"."CAVITESCOP" MODIFY ("NO_PRESSE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PRESSESCOP
--------------------------------------------------------

  ALTER TABLE "AS_MOULES"."PRESSESCOP" MODIFY ("TYPE_STD" NOT NULL ENABLE);
  ALTER TABLE "AS_MOULES"."PRESSESCOP" MODIFY ("TYPE_PRESSE" NOT NULL ENABLE);
  ALTER TABLE "AS_MOULES"."PRESSESCOP" MODIFY ("NB_CAVITES" NOT NULL ENABLE);
  ALTER TABLE "AS_MOULES"."PRESSESCOP" MODIFY ("NO_PRESSE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table LISTE_OP
--------------------------------------------------------

  ALTER TABLE "AS_MOULES"."LISTE_OP" MODIFY ("EQUIPE" NOT NULL ENABLE);
  ALTER TABLE "AS_MOULES"."LISTE_OP" MODIFY ("NOM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TREADSET
--------------------------------------------------------

  ALTER TABLE "AS_MOULES"."TREADSET" MODIFY ("FACT_CODE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BDUSERS
--------------------------------------------------------

  ALTER TABLE "AS_MOULES"."BDUSERS" MODIFY ("USER_NAME" NOT NULL ENABLE);
  ALTER TABLE "AS_MOULES"."BDUSERS" MODIFY ("PLANT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SUIVI_GRADE
--------------------------------------------------------

  ALTER TABLE "AS_MOULES"."SUIVI_GRADE" MODIFY ("NUM_PRESSE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SUIVI_CRYO
--------------------------------------------------------

  ALTER TABLE "AS_MOULES"."SUIVI_CRYO" MODIFY ("DATE_CRYO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EXT_MOLDEQUIPMENTSPEC
--------------------------------------------------------

  ALTER TABLE "AS_MOULES"."EXT_MOLDEQUIPMENTSPEC" MODIFY ("REF_SPEC" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SUIVI_CRYO_OLD
--------------------------------------------------------

  ALTER TABLE "AS_MOULES"."SUIVI_CRYO_OLD" MODIFY ("DATE_CRYO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CMOS
--------------------------------------------------------

  ALTER TABLE "AS_MOULES"."CMOS" MODIFY ("NO_PRESSE" NOT NULL ENABLE);
  ALTER TABLE "AS_MOULES"."CMOS" MODIFY ("NO_CMO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table NUMCMO
--------------------------------------------------------

  ALTER TABLE "AS_MOULES"."NUMCMO" MODIFY ("NO_CMO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PRESSES
--------------------------------------------------------

  ALTER TABLE "AS_MOULES"."PRESSES" MODIFY ("TYPE_STD" NOT NULL ENABLE);
  ALTER TABLE "AS_MOULES"."PRESSES" MODIFY ("TYPE_PRESSE" NOT NULL ENABLE);
  ALTER TABLE "AS_MOULES"."PRESSES" MODIFY ("NB_CAVITES" NOT NULL ENABLE);
  ALTER TABLE "AS_MOULES"."PRESSES" MODIFY ("NO_PRESSE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ARCHIVAGE_SPECS
--------------------------------------------------------

  ALTER TABLE "AS_MOULES"."ARCHIVAGE_SPECS" MODIFY ("REF_SPEC" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SPECS
--------------------------------------------------------

  ALTER TABLE "AS_MOULES"."SPECS" MODIFY ("FACT_CODE" NOT NULL ENABLE);
  ALTER TABLE "AS_MOULES"."SPECS" MODIFY ("TS_CODE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ARCHIVAGE_MOULES
--------------------------------------------------------

  ALTER TABLE "AS_MOULES"."ARCHIVAGE_MOULES" MODIFY ("REF_MOULE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CURES
--------------------------------------------------------

  ALTER TABLE "AS_MOULES"."CURES" MODIFY ("FACT_CODE" NOT NULL ENABLE);
  ALTER TABLE "AS_MOULES"."CURES" MODIFY ("TS_CODE" NOT NULL ENABLE);
